#!/usr/bin/env python3
"""Regression suite for scripts/contract-version.py (Verjson/.github#1374)."""
import importlib.util
import json
import pathlib
import sys
import tempfile
import unittest

_root = pathlib.Path(__file__).resolve().parents[2]
_spec = importlib.util.spec_from_file_location(
    "contract_version", _root / "scripts" / "contract-version.py")
cv = importlib.util.module_from_spec(_spec)
# Registered before execution: `@dataclasses.dataclass` under
# `from __future__ import annotations` resolves field types through
# `sys.modules[cls.__module__]`, which is absent for a module loaded straight
# from a path.
sys.modules["contract_version"] = cv
_spec.loader.exec_module(cv)


def rel(version, commit_char="a", published="2026-01-01"):
    return cv.Release(version=version, commit=commit_char * 40, published=published)


class SupportedWindow(unittest.TestCase):
    def test_window_never_refuses_a_version_package_retention_still_keeps(self):
        # Three minor lines, three releases: "current and previous minor" alone
        # would refuse v3.0.0 while the keep-3 retention policy still considers
        # it current, stranding a consumer the org calls supported.
        releases = [rel("v2.9.0"), rel("v3.0.0"), rel("v3.1.0"), rel("v3.2.0")]
        self.assertEqual(
            cv.supported_versions(releases), {"v3.0.0", "v3.1.0", "v3.2.0"})


class DeprecationClock(unittest.TestCase):
    def test_a_version_pushed_out_of_the_window_expires_90_days_after_the_release_that_did_it(self):
        # v3.0.0 is still supported at v3.2.0 (it is one of the newest three);
        # v3.3.0, published 2026-03-01, is what pushes it out. The deprecation
        # error has to name a date a maintainer can act on, and that date is a
        # function of release metadata rather than a stored deadline.
        releases = [
            rel("v3.0.0", published="2026-01-01"),
            rel("v3.1.0", published="2026-01-15"),
            rel("v3.2.0", published="2026-02-01"),
            rel("v3.3.0", published="2026-03-01"),
        ]
        verdict = cv.classify("v3.0.0", releases, today="2026-04-01")
        self.assertEqual(verdict.state, cv.DEPRECATED)
        self.assertEqual(verdict.expires_on, "2026-05-30")


class DeclarationVersusReality(unittest.TestCase):
    def write_repo(self, declaration, workflow):
        root = pathlib.Path(tempfile.mkdtemp())
        (root / ".github" / "workflows").mkdir(parents=True)
        if declaration is not None:
            (root / ".github" / "verjson-contract.json").write_text(
                json.dumps(declaration))
        (root / ".github" / "workflows" / "ci.yml").write_text(workflow)
        return root

    def test_a_pin_that_is_not_the_declared_release_commit_is_a_finding(self):
        # The failure mode a declared version exists to close: the declaration
        # says v3.2.0 while the repository actually runs some other contract
        # commit. A version nothing reads back is a pin nobody advances.
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo(
            {"contract_version": "v3.2.0"},
            "jobs:\n  ci:\n    uses: Verjson/.github/.github/workflows/node-ci.yml@"
            + "b" * 40 + "\n")
        findings = cv.verify(root, releases, today="2026-02-02")
        self.assertEqual([f.kind for f in findings], ["PIN_MISMATCH"])
        self.assertIn(".github/workflows/ci.yml", findings[0].detail)

    def test_a_moving_tag_is_not_an_immutable_contract_reference(self):
        # `@v3` resolves to whatever the hub last re-pointed it at, so it can
        # name a different contract tomorrow while the declaration stays put.
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo(
            {"contract_version": "v3.2.0"},
            "jobs:\n  ci:\n    uses: Verjson/.github/.github/workflows/node-ci.yml@v3\n")
        findings = cv.verify(root, releases, today="2026-02-02")
        self.assertEqual([f.kind for f in findings], ["UNPINNED_REFERENCE"])

    def test_a_consistent_repository_reports_nothing(self):
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo(
            {"contract_version": "v3.2.0"},
            "# Generated by Verjson/.github scripts/gen-changelog-caller.sh workflow "
            + "a" * 40 + "\njobs:\n  ci:\n    uses: "
            "Verjson/.github/.github/workflows/node-ci.yml@" + "a" * 40 + "\n")
        self.assertEqual(cv.verify(root, releases, today="2026-02-02"), [])

    def test_a_generated_header_claiming_another_contract_is_a_finding(self):
        # The intra-repository skew shape: the caller is repinned and the header
        # the generator stamped still names the contract it was generated at.
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo(
            {"contract_version": "v3.2.0"},
            "# Generated by Verjson/.github scripts/gen-changelog-caller.sh workflow "
            + "c" * 40 + "\njobs:\n  ci:\n    uses: "
            "Verjson/.github/.github/workflows/node-ci.yml@" + "a" * 40 + "\n")
        findings = cv.verify(root, releases, today="2026-02-02")
        self.assertEqual([f.kind for f in findings], ["PIN_MISMATCH"])
        self.assertIn("header", findings[0].detail)

    def test_references_without_a_declaration_are_reported(self):
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo(
            None,
            "jobs:\n  ci:\n    uses: Verjson/.github/.github/workflows/node-ci.yml@"
            + "a" * 40 + "\n")
        self.assertEqual([f.kind for f in cv.verify(root, releases, today="2026-02-02")],
                         ["DECLARATION_MISSING"])

    def test_a_declaration_governing_nothing_is_reported(self):
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo({"contract_version": "v3.2.0"}, "jobs:\n  ci:\n    steps: []\n")
        self.assertEqual([f.kind for f in cv.verify(root, releases, today="2026-02-02")],
                         ["UNGOVERNED_DECLARATION"])

    def test_a_repository_that_adopts_nothing_is_not_an_adopter(self):
        # No declaration and no reference is not a defect: it is a repository
        # that does not consume the contract. Reporting it would make the check
        # fire on every repository in the organization and get muted.
        releases = [rel("v3.2.0", commit_char="a", published="2026-02-01")]
        root = self.write_repo(None, "jobs:\n  ci:\n    steps: []\n")
        self.assertEqual(cv.verify(root, releases, today="2026-02-02"), [])

    def test_an_unresolved_release_commit_fails_closed(self):
        # `target_commitish` is a branch name for many releases; comparing a pin
        # against "main" would report every adopter broken.
        releases = [cv.Release(version="v3.2.0", commit="main", published="2026-02-01")]
        root = self.write_repo(
            {"contract_version": "v3.2.0"},
            "jobs:\n  ci:\n    uses: Verjson/.github/.github/workflows/node-ci.yml@"
            + "a" * 40 + "\n")
        self.assertEqual([f.kind for f in cv.verify(root, releases, today="2026-02-02")],
                         [cv.UNKNOWN])


class WindowEdges(unittest.TestCase):
    def test_moving_and_non_contract_tags_never_occupy_a_window_slot(self):
        # The hub really carries `v1`, `v2`, and `runner-canary-v1.0.0`. A moving
        # tag holding a slot would shrink the window to two real releases.
        releases = [rel("v3.0.0"), rel("v3.1.0"), rel("v3.2.0"),
                    rel("v3"), rel("runner-canary-v1.0.0")]
        self.assertEqual(cv.supported_versions(releases),
                         {"v3.0.0", "v3.1.0", "v3.2.0"})

    def test_no_releases_supports_nothing(self):
        self.assertEqual(cv.supported_versions([]), set())

    def test_an_unreleased_version_is_unknown_not_supported(self):
        self.assertEqual(cv.classify("v9.9.9", [rel("v3.0.0")], today="2026-02-02").state,
                         cv.UNKNOWN)

    def test_a_malformed_version_is_unknown(self):
        self.assertEqual(cv.classify("main", [rel("v3.0.0")], today="2026-02-02").state,
                         cv.UNKNOWN)

    def test_crossing_a_major_buys_the_longer_clock(self):
        releases = [
            rel("v3.0.0", published="2026-01-01"),
            rel("v3.1.0", published="2026-01-15"),
            rel("v3.2.0", published="2026-02-01"),
            rel("v4.0.0", published="2026-03-01"),
        ]
        verdict = cv.classify("v3.0.0", releases, today="2026-04-01")
        self.assertEqual(verdict.state, cv.DEPRECATED)
        self.assertEqual(verdict.expires_on, "2026-08-28")

    def test_the_deprecation_becomes_a_refusal_on_its_stated_date(self):
        releases = [
            rel("v3.0.0", published="2026-01-01"),
            rel("v3.1.0", published="2026-01-15"),
            rel("v3.2.0", published="2026-02-01"),
            rel("v3.3.0", published="2026-03-01"),
        ]
        self.assertEqual(cv.classify("v3.0.0", releases, today="2026-05-30").state,
                         cv.EXPIRED)


class CommandLine(unittest.TestCase):
    def releases_file(self, payload):
        handle = tempfile.NamedTemporaryFile("w", suffix=".json", delete=False)
        json.dump(payload, handle)
        handle.close()
        return handle.name

    def test_verify_exits_nonzero_when_the_declaration_does_not_match_the_tree(self):
        root = pathlib.Path(tempfile.mkdtemp())
        (root / ".github" / "workflows").mkdir(parents=True)
        (root / ".github" / "verjson-contract.json").write_text(
            json.dumps({"contract_version": "v3.2.0"}))
        (root / ".github" / "workflows" / "ci.yml").write_text(
            "jobs:\n  ci:\n    uses: Verjson/.github/.github/workflows/node-ci.yml@"
            + "b" * 40 + "\n")
        releases = self.releases_file(
            [{"version": "v3.2.0", "commit": "a" * 40, "published": "2026-02-01"}])
        self.assertEqual(
            cv.main(["verify", "--repo-root", str(root), "--releases", releases,
                     "--today", "2026-02-02"]), 1)

    def test_a_releases_file_that_cannot_be_read_is_a_usage_failure_not_a_verdict(self):
        # A sweep that lost its input must not report the tree it never compared
        # as conformant; exit 2 is "the question could not be asked".
        self.assertEqual(
            cv.main(["verify", "--repo-root", ".", "--releases", "/nonexistent.json",
                     "--today", "2026-02-02"]), 2)


if __name__ == "__main__":
    unittest.main()
