const assert = require("node:assert/strict");
const { spawnSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { after, before, test } = require("node:test");

const repositoryRoot = path.resolve(__dirname, "../..");
const manifestPath = path.join(repositoryRoot, "package.json");
const releaseWorkflowPath = path.join(repositoryRoot, ".github/workflows/release.yml");
let temporaryRoot;
let installedPackage;
let consumerRoot;
let packageManifest;
let packageArchive;
let packedPackage;

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { encoding: "utf8", ...options });
  assert.equal(result.error, undefined, result.error?.message);
  assert.equal(result.status, 0, result.stderr || `${command} exited ${result.status}`);
  return result.stdout;
}

before(() => {
  temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), "verjson-contract-package-"));
  packageManifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

  const packOutput = JSON.parse(
    run("npm", ["pack", "--json", "--ignore-scripts", "--pack-destination", temporaryRoot], {
      cwd: repositoryRoot,
    }),
  );
  const packed = Array.isArray(packOutput) ? packOutput : Object.values(packOutput);
  assert.equal(packed.length, 1, "npm pack should produce one contract package");
  packedPackage = packed[0];
  packageArchive = path.join(temporaryRoot, packedPackage.filename);

  consumerRoot = path.join(temporaryRoot, "consumer");
  installedPackage = path.join(consumerRoot, "node_modules/@verjson/contract");
  fs.mkdirSync(installedPackage, { recursive: true });
  run("tar", ["-xzf", packageArchive, "-C", installedPackage, "--strip-components=1"]);

  const binaryDirectory = path.join(consumerRoot, "node_modules/.bin");
  fs.mkdirSync(binaryDirectory, { recursive: true });
  for (const [name, relativeTarget] of Object.entries(packageManifest.bin || {})) {
    fs.symlinkSync(
      path.relative(binaryDirectory, path.join(installedPackage, relativeTarget)),
      path.join(binaryDirectory, name),
    );
  }
});

after(() => {
  if (temporaryRoot) fs.rmSync(temporaryRoot, { recursive: true, force: true });
});

test("publishes the two contract tools as a version-locked GitHub Packages package", () => {
  assert.equal(packageManifest.name, "@verjson/contract");
  assert.notEqual(packageManifest.private, true);
  assert.equal(packageManifest.publishConfig?.registry, "https://npm.pkg.github.com");
  assert.deepEqual(Object.keys(packageManifest.bin).sort(), ["gen-adr-index", "render-next"]);
  assert.equal(packedPackage.name, packageManifest.name);
  assert.equal(packedPackage.version, packageManifest.version);

  const packageLock = JSON.parse(fs.readFileSync(path.join(repositoryRoot, "package-lock.json"), "utf8"));
  assert.equal(packageLock.packages[""].name, packageManifest.name);
  assert.equal(packageLock.packages[""].version, packageManifest.version);
  assert.match(packageManifest.version, /^\d+\.\d+\.\d+$/);
  if (process.env.PACKAGE_VERSION) assert.equal(packageManifest.version, process.env.PACKAGE_VERSION);

  const releaseWorkflow = fs.readFileSync(releaseWorkflowPath, "utf8");
  const generatedHeader = releaseWorkflow.match(/^# Generated by verJSON\/\.github scripts\/gen-changelog-caller\.sh (.+)$/m);
  assert.ok(generatedHeader, "release workflow should be generated by the canonical caller generator");
  assert.match(generatedHeader[1], /^release-node [0-9a-f]{40} --only-package-dir \.\s*$/);
  const contractSha = generatedHeader[1].match(/^release-node ([0-9a-f]{40})/)[1];
  assert.match(releaseWorkflow, /package-dirs: '\["\."\]'/);
  assert.ok(releaseWorkflow.includes(`contract_ref: ${contractSha}`));
  assert.ok(releaseWorkflow.includes(`node-release.yml@${contractSha}`));

  const packedFiles = run("tar", ["-tzf", packageArchive]);
  assert.deepEqual(packedFiles.trim().split("\n").sort(), [
    "package/README.md",
    "package/bin/gen-adr-index.js",
    "package/bin/render-next.js",
    "package/package.json",
    "package/scripts/changelog.py",
    "package/scripts/gen-adr-index.sh",
  ]);
});

test("render-next reads the consumer's NEXT directory when run from its package bin", () => {
  const nextDirectory = path.join(consumerRoot, "NEXT");
  fs.mkdirSync(nextDirectory, { recursive: true });
  fs.writeFileSync(
    path.join(nextDirectory, "2026-09-28-issue-1374-contract-tools.md"),
    "---\ndate: 2026-09-28\nissue: 1374\nimpact: patch\ntitle: Publish contract developer tools\n---\n\nThe contract tools are available as package bins.\n",
  );

  const output = run(path.join(consumerRoot, "node_modules/.bin/render-next"), [], { cwd: consumerRoot });
  assert.match(output, /^## Publish contract developer tools$/m);
  assert.match(output, /available as package bins/);
});

test("render-next preserves a nonzero result when no fragments are available", () => {
  const emptyConsumer = path.join(temporaryRoot, "empty-consumer");
  fs.mkdirSync(emptyConsumer);

  const result = spawnSync(path.join(consumerRoot, "node_modules/.bin/render-next"), [], {
    cwd: emptyConsumer,
    encoding: "utf8",
  });
  assert.equal(result.error, undefined, result.error?.message);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /no unreleased fragments/);
});

test("gen-adr-index updates and checks the consumer's decision index", () => {
  const decisionsDirectory = path.join(consumerRoot, "docs/decisions");
  fs.mkdirSync(path.join(decisionsDirectory, "0001-contract-tools"), { recursive: true });
  fs.writeFileSync(
    path.join(decisionsDirectory, "README.md"),
    "# Decisions\n\n<!-- BEGIN ADR INDEX -->\n<!-- END ADR INDEX -->\n",
  );
  fs.writeFileSync(
    path.join(decisionsDirectory, "0001-contract-tools/README.md"),
    "# 0001 — Contract tools\n\n- **Date:** 2026-09-28\n",
  );

  run(path.join(consumerRoot, "node_modules/.bin/gen-adr-index"), [], { cwd: consumerRoot });
  const index = fs.readFileSync(path.join(decisionsDirectory, "README.md"), "utf8");
  assert.match(index, /\| \[0001\]\(0001-contract-tools\/README\.md\) \| 2026-09-28 \| Contract tools \|/);
  run(path.join(consumerRoot, "node_modules/.bin/gen-adr-index"), ["--check"], { cwd: consumerRoot });

  fs.writeFileSync(path.join(decisionsDirectory, "README.md"), "# Decisions\n\n<!-- BEGIN ADR INDEX -->\n<!-- END ADR INDEX -->\n");
  const staleIndex = spawnSync(path.join(consumerRoot, "node_modules/.bin/gen-adr-index"), ["--check"], {
    cwd: consumerRoot,
    encoding: "utf8",
  });
  assert.equal(staleIndex.error, undefined, staleIndex.error?.message);
  assert.notEqual(staleIndex.status, 0);
});

test("gen-adr-index normalizes unexpected child exit codes to 1", () => {
  const fakeBinDirectory = path.join(temporaryRoot, "fake-bash-bin");
  const fakeBash = path.join(fakeBinDirectory, "bash");
  fs.mkdirSync(fakeBinDirectory, { recursive: true });
  fs.writeFileSync(fakeBash, "#!/bin/sh\nexit 137\n");
  fs.chmodSync(fakeBash, 0o755);

  const result = spawnSync(path.join(consumerRoot, "node_modules/.bin/gen-adr-index"), [], {
    cwd: consumerRoot,
    encoding: "utf8",
    env: { ...process.env, PATH: `${fakeBinDirectory}${path.delimiter}${process.env.PATH ?? ""}` },
  });
  assert.equal(result.error, undefined, result.error?.message);
  assert.equal(result.status, 1, result.stderr);
});

test("gen-adr-index preserves its documented argument-error exit code 2", () => {
  const result = spawnSync(
    path.join(consumerRoot, "node_modules/.bin/gen-adr-index"),
    ["--unsupported"],
    { cwd: consumerRoot, encoding: "utf8" },
  );
  assert.equal(result.error, undefined, result.error?.message);
  assert.equal(result.status, 2, result.stderr);
});
