#!/usr/bin/env python3
"""Regression suite for scripts/fleet-contract-inventory.py.

The assertion that matters is the fail-open one: a sweep that cannot resolve a
ref must report UNKNOWN, never CURRENT. The invalid predecessor test reported
"current" whenever both of its API calls failed, which is how the `#184` drift
survived a sweep written to find it.
"""
import base64
import importlib.util
import json
import pathlib
import sys
import unittest

_root = pathlib.Path(__file__).resolve().parents[2]


def _load(name, filename):
    spec = importlib.util.spec_from_file_location(name, _root / "scripts" / filename)
    module = importlib.util.module_from_spec(spec)
    # Registered before execution: a `@dataclasses.dataclass` under
    # `from __future__ import annotations` resolves its field types through
    # `sys.modules[cls.__module__]`, which is absent for a path-loaded module.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


fci = _load("fleet_contract_inventory", "fleet-contract-inventory.py")
reporter = _load("fleet_contract_report", "render-fleet-contract-inventory-report.py")
# Loaded here so the agreement between the two sweeps can be asserted rather
# than maintained by hand -- Verjson/.github#1482.
cv = _load("contract_version", "contract-version.py")
# Imported rather than path-loaded, and that matters for the identity
# assertions below: `_load` would build a *second* module object with its own
# function objects, and `fci.references is contract_reference.references` would
# then fail for a reason that has nothing to do with the sweep. The inventory
# puts `scripts/` on `sys.path` and imports this module, so a plain import here
# binds the very object it imported from.
import contract_reference  # noqa: E402

A = "a" * 40
B = "b" * 40
PATH = ".github/workflows/node-ci.yml"


class Classify(unittest.TestCase):
    def test_equal_resolved_object_ids_are_current(self):
        self.assertEqual(fci.classify(PATH, {PATH: A}, {PATH: A}), "CURRENT")

    def test_differing_resolved_object_ids_are_drifted(self):
        self.assertEqual(fci.classify(PATH, {PATH: A}, {PATH: B}), "DRIFTED")

    def test_an_unresolvable_pinned_tree_is_unknown_not_current(self):
        self.assertEqual(fci.classify(PATH, None, {PATH: A}), "UNKNOWN")

    def test_an_unresolvable_default_tree_is_unknown_not_current(self):
        self.assertEqual(fci.classify(PATH, {PATH: A}, None), "UNKNOWN")

    def test_two_unresolvable_trees_do_not_compare_equal(self):
        # The exact predecessor defect: `[ "" = "" ]` is true.
        self.assertEqual(fci.classify(PATH, None, None), "UNKNOWN")

    def test_a_path_absent_from_either_tree_is_unknown(self):
        self.assertEqual(fci.classify(PATH, {}, {PATH: A}), "UNKNOWN")
        self.assertEqual(fci.classify(PATH, {PATH: A}, {}), "UNKNOWN")

    def test_two_empty_trees_do_not_compare_equal(self):
        self.assertEqual(fci.classify(PATH, {}, {}), "UNKNOWN")

    def test_a_malformed_object_id_is_unknown_not_current(self):
        self.assertEqual(fci.classify(PATH, {PATH: "not-a-sha"},
                                      {PATH: "not-a-sha"}), "UNKNOWN")


class UsesExtraction(unittest.TestCase):
    def test_extracts_path_and_pin_from_a_hub_reference(self):
        text = f"    uses: Verjson/.github/.github/workflows/node-ci.yml@{A}\n"
        self.assertEqual(sorted(fci.pins(text)),
                         [(".github/workflows/node-ci.yml", A)])

    def test_ignores_a_reference_to_another_owner(self):
        text = f"    uses: OtherOrg/.github/.github/workflows/node-ci.yml@{A}\n"
        self.assertEqual(sorted(fci.pins(text)), [])

    def test_ignores_a_moving_tag_because_it_is_not_a_pin(self):
        text = "    uses: Verjson/.github/.github/workflows/node-ci.yml@v1\n"
        # Still a *reference* -- `contract-version` reports it as an unpinned
        # one -- but not a pin, so it is not this sweep's row. The narrowing
        # moved from the pattern to `pins()`; what it admits did not.
        self.assertEqual(sorted(fci.pins(text)), [])
        self.assertEqual([m.group("ref") for m in fci.USES_RE.finditer(text)],
                         ["v1"])

    def test_finds_every_distinct_pin_in_one_file(self):
        text = (f"  uses: Verjson/.github/.github/workflows/node-ci.yml@{A}\n"
                f"  uses: Verjson/.github/.github/workflows/changelog.yml@{B}\n")
        self.assertEqual({sha for _, sha in fci.pins(text)}, {A, B})


class HeaderClaimExtraction(unittest.TestCase):
    """A header SHA is a claim to compare, never an invocation to execute."""

    def test_reads_a_generated_header_contract_sha(self):
        head = f"# Generated by Verjson/.github scripts/gen-changelog-caller.sh full {A}\n"
        self.assertEqual({m.group("sha") for m in fci.HEADER_RE.finditer(head)},
                         {A})

    def test_a_container_digest_does_not_yield_a_truncated_contract_sha(self):
        # Without a trailing boundary the first 40 of these 64 hex characters
        # parse as a contract SHA, and the file reports a bogus header split.
        digest = "c" * 64
        head = f"# Generated by Verjson/.github image ghcr.io/x@sha256:{digest}\n"
        self.assertEqual(list(fci.HEADER_RE.finditer(head)), [])

    def test_a_reference_to_another_owner_is_not_a_hub_claim(self):
        head = f"# Generated by OtherOrg/.github scripts/gen.sh full {A}\n"
        self.assertEqual(list(fci.HEADER_RE.finditer(head)), [])


class UsesBoundaries(unittest.TestCase):

    def test_matches_a_lowercase_owner_because_github_is_case_insensitive(self):
        text = f"    uses: verjson/.github/.github/workflows/node-ci.yml@{A}\n"
        self.assertEqual([sha for _, sha in fci.pins(text)], [A])

    def test_a_longer_hex_run_is_not_a_pin(self):
        text = f"    uses: Verjson/.github/.github/workflows/node-ci.yml@{'a' * 64}\n"
        # The boundary is now `SHA_RE`'s anchoring rather than a `(?![0-9a-f])`
        # lookahead inside the pattern: the whole 64-hex run is the ref, and a
        # 64-character ref is not a 40-hex commit. The reference is still seen,
        # which is what lets `contract-version` report it.
        self.assertEqual(sorted(fci.pins(text)), [])
        self.assertEqual([m.group("ref") for m in fci.USES_RE.finditer(text)],
                         ["a" * 64])


class FlowStyleAndTrailingStructure(unittest.TestCase):
    """Verjson/.github#1482. Unifying the two recognizers narrowed what the
    *inventory* accepts, in the muting direction the shared module exists to
    prevent. The pattern this sweep used before the unification required exactly
    40 hex and closed on `(?![0-9a-f])`; the shared one read any ref out of a
    class that ran straight through `}`, `]` and `,`, so a pin in flow-style
    YAML came back as `<sha>}]` and failed `SHA_RE` -- a repository carrying a
    pin looked clean. Latent, not active: no adopter in the measured fleet
    writes a step this way, which is why it is cheap to close now.

    Every fixture here carries two pins rather than one. With a single pin the
    class that stops at the structure and the class that runs through it differ
    only in one ref's content; written adjacently they differ in the number of
    matches, which is the assertion a single-instance fixture cannot make.
    """

    def test_a_flow_style_mapping_carries_pins_the_sweep_must_read(self):
        # Ordinary YAML: this parses to exactly the structure the block form
        # does, and it is `.github/workflows/*.yml` that this sweep reads.
        text = ("    steps: [{uses: Verjson/.github/.github/workflows/node-ci.yml@"
                f"{A}}}, {{uses: Verjson/.github/.github/workflows/changelog.yml@{B}}}]\n")
        self.assertEqual(sorted(fci.pins(text)),
                         [(".github/workflows/changelog.yml", B),
                          (".github/workflows/node-ci.yml", A)])

    def test_a_single_pair_flow_sequence_entry_carries_pins(self):
        # A flow sequence entry may be a single key/value pair with no braces
        # at all; YAML parses it to the same mapping. `[` therefore opens a key
        # position exactly as `{` does.
        text = ("    steps: [ uses: Verjson/.github/.github/workflows/node-ci.yml@"
                f"{A}, uses: Verjson/.github/.github/workflows/changelog.yml@{B} ]\n")
        self.assertEqual(sorted(fci.pins(text)),
                         [(".github/workflows/changelog.yml", B),
                          (".github/workflows/node-ci.yml", A)])

    def test_a_pin_is_not_muted_by_a_trailing_escape_or_comma(self):
        # The source-string shape the delimiter class already reads on its
        # opening side: `\n` closes the value too, and before this the ref came
        # back 41 characters -- correct, immutable, and unable to compare equal
        # to any release commit.
        text = (f'    body = "uses: Verjson/.github/.github/workflows/node-ci.yml@{A}\\n"\n'
                f'    tail = "uses: Verjson/.github/.github/workflows/changelog.yml@{B},"\n')
        self.assertEqual(sorted(fci.pins(text)),
                         [(".github/workflows/changelog.yml", B),
                          (".github/workflows/node-ci.yml", A)])

    def test_a_hex_run_that_continues_into_a_refname_is_not_a_pin(self):
        # The widening side of the boundary, and the reason it is `(?![\w./+-])`
        # rather than the `(?![0-9a-f])` it replaces. A tag named after a commit
        # with a suffix is not that commit; reporting its first 40 characters as
        # a pin invents a PIN_MISMATCH, which is the direction strictly worse
        # than the muting one. Both fall through to the general class and stay
        # whole references.
        text = (f"    uses: Verjson/.github/.github/workflows/node-ci.yml@{A}-rc1\n"
                f"    uses: Verjson/.github/.github/workflows/changelog.yml@{B}.1\n")
        self.assertEqual(sorted(fci.pins(text)), [])
        # Through `references()` rather than `USES_RE.finditer`: the fixture is
        # two lines, and the per-line application is the API both sweeps use.
        self.assertEqual([ref for _, ref in fci.references(text)],
                         [f"{A}-rc1", f"{B}.1"])

    def test_a_substitution_ref_keeps_its_braces(self):
        # The reason the general class still admits `{` and `}`: this corpus
        # writes refs as generator and fixture substitutions, and excluding
        # those characters drops such a reference entirely rather than reporting
        # it unpinned. Two of them, so an over-narrowed class changes the count.
        text = ("    uses: Verjson/.github/.github/workflows/node-ci.yml@${ref}\n"
                "    uses: Verjson/.github/.github/workflows/changelog.yml@{PIN}\n")
        self.assertEqual(sorted(fci.pins(text)), [])
        self.assertEqual([ref for _, ref in fci.references(text)],
                         ["${ref}", "{PIN}"])


class UnreachableIsNotEmpty(unittest.TestCase):
    """`{}` means "no workflows"; a failed listing must not say the same thing."""

    def setUp(self):
        self._gh_run = fci.gh_run
        self.addCleanup(lambda: setattr(fci, "gh_run", self._gh_run))

    def _serve(self, out, err=""):
        fci.gh_run = lambda *a: (out, err)

    def test_a_failed_listing_is_unreachable_not_empty(self):
        # No HTTP status at all: a transport or auth fault, not an answer.
        self._serve(None, "dial tcp: connection refused")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_unparseable_listing_is_unreachable_not_empty(self):
        self._serve("not json")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_an_empty_listing_is_empty_not_unreachable(self):
        self._serve("[]")
        self.assertEqual(fci.workflows("Verjson/example"), {})

    def test_a_successful_call_returning_no_bytes_is_empty_not_unreachable(self):
        # `out is not None` and `out` are not the same test. A call that
        # succeeded with an empty body is an answer, and downgrading it to
        # unreachable is the conflation this class forbids, just inverted.
        self._serve("")
        self.assertEqual(fci.workflows("Verjson/example"), {})


class DirectoryListingCap(unittest.TestCase):
    """The contents endpoint is unpaginated, and silently caps at 1,000 entries.

    It returns a whole directory in one response — 49 entries for the hub's own
    `.github/workflows` with no `Link` header — so there is no page to follow
    and `--paginate` would change nothing. What it does do is stop at 1,000
    entries, and a sweep that reports completeness cannot take a capped listing
    for the whole directory.
    """

    def setUp(self):
        self._gh, self._gh_run = fci.gh, fci.gh_run
        self._unreadable = list(fci.unreadable)
        self._incomplete = list(fci.incomplete_listings)
        self.addCleanup(lambda: setattr(fci, "gh", self._gh))
        self.addCleanup(lambda: setattr(fci, "gh_run", self._gh_run))
        self.addCleanup(lambda: fci.unreadable.__setitem__(
            slice(None), self._unreadable))
        self.addCleanup(lambda: fci.incomplete_listings.__setitem__(
            slice(None), self._incomplete))
        fci.unreadable.clear()
        fci.incomplete_listings.clear()

    @staticmethod
    def _listing(count: int) -> str:
        return json.dumps([{"name": f"w{i}.yml", "type": "file", "sha": A}
                           for i in range(count)])

    def _serve(self, count: int):
        listing = self._listing(count)
        fci.gh_run = lambda *a: (listing, "")
        fci.gh = lambda *a: base64.b64encode(b"on: push\n").decode()

    def test_a_listing_at_the_cap_is_reported_as_a_gap(self):
        self._serve(fci.CONTENTS_DIR_LIMIT)
        files = fci.workflows("Verjson/example")
        self.assertTrue(any("Verjson/example:.github/workflows" in gap
                            for gap in fci.incomplete_listings),
                        "a capped listing must name itself as a gap")
        # The gap is named, not raised: the entries that WERE returned are still
        # classified, so a capped repository contributes rows and a gap rather
        # than vanishing from the report entirely.
        self.assertEqual(len(files), fci.CONTENTS_DIR_LIMIT)
        # A capped directory is not an unreadable path, and conflating the two
        # would make the unreadable-file count mean two different things.
        self.assertEqual(fci.unreadable, [])

    def test_a_listing_below_the_cap_reports_no_gap(self):
        self._serve(3)
        self.assertEqual(len(fci.workflows("Verjson/example")), 3)
        self.assertEqual(fci.unreadable, [])
        self.assertEqual(fci.incomplete_listings, [])




class UnreadTextIsNeverTakenForWorkflowText(unittest.TestCase):
    """Every path that fails to read a workflow must name its own gap.

    A blob that was not read contributes no `uses:` pins, which is
    indistinguishable from a workflow that references the hub nowhere. So a
    silent drop here does not merely lose a file — it reports the file as
    carrying no drift.
    """

    def setUp(self):
        self._gh, self._gh_run = fci.gh, fci.gh_run
        self._unreadable = list(fci.unreadable)
        self.addCleanup(lambda: setattr(fci, "gh", self._gh))
        self.addCleanup(lambda: setattr(fci, "gh_run", self._gh_run))
        self.addCleanup(lambda: fci.unreadable.__setitem__(
            slice(None), self._unreadable))
        fci.unreadable.clear()

    def _serve(self, blob: str):
        listing = json.dumps([{"name": "a.yml", "type": "file", "sha": A}])
        fci.gh_run = lambda *a: (listing, "")
        fci.gh = lambda *a: blob

    def test_a_null_content_field_is_unreadable_not_three_bytes_of_text(self):
        # `--jq .content` prints the literal string `null` for the `encoding:
        # none` shape GitHub uses for an oversized blob. It is valid base64.
        self._serve("null\n")
        self.assertEqual(fci.workflows("Verjson/example"), {})
        self.assertEqual(fci.unreadable, ["Verjson/example:.github/workflows/a.yml"])

    def test_an_undecodable_blob_is_unreadable_not_silently_dropped(self):
        self._serve("!!!not-base64!!!")
        self.assertEqual(fci.workflows("Verjson/example"), {})
        self.assertEqual(fci.unreadable, ["Verjson/example:.github/workflows/a.yml"])

    def test_a_listing_that_is_not_an_array_is_unreachable_not_empty(self):
        # `{"message": "Not Found"}` must not read as "this repo has no
        # workflows"; that is the conflation the docstring forbids.
        fci.gh_run = lambda *a: ('{"message": "Not Found"}', "")
        self.assertIsNone(fci.workflows("Verjson/example"))


class TruncatedHubTreeIsAGap(unittest.TestCase):
    def setUp(self):
        self._gh = fci.gh
        self._truncated = list(fci.truncated_trees)
        fci._tree_cache.clear()
        self.addCleanup(lambda: setattr(fci, "gh", self._gh))
        self.addCleanup(fci._tree_cache.clear)
        self.addCleanup(lambda: fci.truncated_trees.__setitem__(
            slice(None), self._truncated))
        fci.truncated_trees.clear()

    def test_a_truncated_tree_names_itself_rather_than_only_going_unknown(self):
        # Every row resolved against a short tree is an unsupported conclusion,
        # not an observation. UNKNOWN in the tally does not distinguish it from
        # a ref that simply does not resolve, and does not reach the exit code.
        fci.gh = lambda *a: json.dumps({"truncated": True, "tree": []})
        self.assertIsNone(fci.hub_tree(A))
        self.assertTrue(any(A in gap for gap in fci.truncated_trees))


class ExitCodeReportsIncompleteness(unittest.TestCase):
    """The whole point of naming a gap kind is that it reaches the exit code.

    Without this, the gap lists could be deleted from the predicate and every
    collection test would still pass while the sweep reported a clean run.
    """

    def setUp(self):
        # `unreachable` is a local of `main()` rather than a module list, so
        # it cannot be seeded from here; the three module-level gap kinds are
        # what this covers.
        for name in ("unreadable", "incomplete_listings", "truncated_trees"):
            saved = list(getattr(fci, name))
            self.addCleanup(
                lambda n=name, s=saved: getattr(fci, n).__setitem__(slice(None), s))
            getattr(fci, name).clear()
        self._gh, self._gh_run = fci.gh, fci.gh_run
        self.addCleanup(lambda: setattr(fci, "gh", self._gh))
        self.addCleanup(lambda: setattr(fci, "gh_run", self._gh_run))
        fci._tree_cache.clear()
        self.addCleanup(fci._tree_cache.clear)

    def _run(self):
        # No repositories to sweep: the rows are irrelevant to the predicate,
        # and this keeps the test about the exit code alone.
        # Both seams, or an unstubbed one reaches the network: `workflows()`
        # lists through `gh_run` and only reads blobs through `gh`.
        def stub(*a):
            return (json.dumps({"truncated": False, "tree": []})
                    if "/git/trees/" in a[-1] else "[]")
        fci.gh = stub
        fci.gh_run = lambda *a: (stub(*a), "")
        return fci.main()

    def test_a_sweep_with_no_gaps_exits_zero(self):
        self.assertEqual(self._run(), 0)

    def test_each_gap_kind_alone_makes_the_sweep_exit_nonzero(self):
        for name in ("unreadable", "incomplete_listings", "truncated_trees"):
            with self.subTest(gap=name):
                getattr(fci, name).append("Verjson/example")
                self.assertEqual(self._run(), 1)
                getattr(fci, name).clear()


class AnAbsentDirectoryIsNotAGap(unittest.TestCase):
    """A repo with nothing to inventory is an observation, not a failure.

    Eleven fleet repos have no `.github/workflows`, and three have no commits
    at all. Both 404. Reporting all fourteen as unreachable inflates the gap
    tally and exits the sweep nonzero for a benign reason — the mirror image of
    the fail-open the tool exists to close, and how a check earns a mute.
    """

    def setUp(self):
        self._gh, self._gh_run = fci.gh, fci.gh_run
        self._absent = list(fci.absent_directories)
        self.addCleanup(lambda: setattr(fci, "gh", self._gh))
        self.addCleanup(lambda: setattr(fci, "gh_run", self._gh_run))
        self.addCleanup(lambda: fci.absent_directories.__setitem__(
            slice(None), self._absent))
        fci.absent_directories.clear()

    def _fails_with(self, stderr: str, root=("[]", ""), repo_readable=True):
        """The workflows listing fails; the confirming calls answer as given."""
        fci.gh = lambda *a: "Verjson/example" if repo_readable else None

        def gh_run(*args):
            target = args[-1]
            if target.endswith("/contents/"):
                return root
            if "/commits" in target:
                return None, "gh: Git Repository is empty. (HTTP 409)\n"
            return None, stderr

        fci.gh_run = gh_run

    def test_a_missing_workflows_directory_is_no_workflows(self):
        self._fails_with("gh: Not Found (HTTP 404)\n")
        self.assertEqual(fci.workflows("Verjson/example"), {})

    def test_an_empty_repository_is_no_workflows(self):
        # GitHub words this one differently from a missing path, and its root
        # 404s too -- the 409 from `commits` is what confirms it has no commits
        # rather than no permission.
        self._fails_with("gh: This repository is empty. (HTTP 404)\n",
                         root=(None, "gh: This repository is empty. (HTTP 404)\n"))
        self.assertEqual(fci.workflows("Verjson/example"), {})

    def test_an_absent_directory_is_named_in_the_report(self):
        self._fails_with("gh: Not Found (HTTP 404)\n")
        self.assertEqual(fci.workflows("Verjson/example"), {})
        self.assertEqual(fci.absent_directories,
                         ["Verjson/example:.github/workflows"])

    def test_a_repo_that_vanished_mid_sweep_is_unreachable_not_absent(self):
        # Deleted, made private, transferred, or dropped from an App
        # installation: all answer 404 exactly like a missing directory, and
        # all are real gaps. Only the confirming call separates them.
        self._fails_with("gh: Not Found (HTTP 404)\n", repo_readable=False)
        self.assertIsNone(fci.workflows("Verjson/example"))
        self.assertEqual(fci.absent_directories, [])

    def test_a_lost_contents_grant_is_unreachable_not_absent(self):
        # The repo still reads, but its root 404s and it is not empty either --
        # so Contents access went away rather than the directory.
        self._fails_with("gh: Not Found (HTTP 404)\n",
                         root=(None, "gh: Not Found (HTTP 404)\n"))
        fci.gh_run = (lambda inner: lambda *a: (
            (None, "gh: Not Found (HTTP 404)\n") if "/commits" in a[-1]
            else inner(*a)))(fci.gh_run)
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_a_forbidden_listing_is_still_unreachable(self):
        # The org enumeration that produced this repo used the same token, so
        # losing read access mid-sweep is a real gap, not an empty repo.
        self._fails_with("gh: Resource not accessible (HTTP 403)\n")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_a_server_error_is_still_unreachable(self):
        self._fails_with("gh: Internal Server Error (HTTP 500)\n")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_a_failure_with_no_status_at_all_is_unreachable(self):
        # A timeout reports no HTTP status. Absent evidence of absence is not
        # evidence of absence: it must not be read as "the directory is gone".
        self._fails_with("timed out")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_a_404_in_the_prose_does_not_stand_in_for_the_status(self):
        # gh puts its status last on the line, so the trailing one is the
        # verdict and a `(HTTP 404)` earlier in the same message is prose. The
        # decoy has to be spelled that way round or it proves nothing.
        self._fails_with("gh: see the docs about (HTTP 404) (HTTP 502)\n")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_only_ghs_own_verdict_line_is_read_as_the_status(self):
        # Taking the last `(HTTP nnn)` anywhere in stderr is not the same as
        # taking gh's verdict: anything gh echoes after it -- a response body,
        # a hint -- would outrank the verdict and turn a 502 into a benign
        # absence. Only a line gh itself prefixed counts.
        self._fails_with("gh: failed (HTTP 502)\nthe server said: (HTTP 404)\n")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_a_verdict_line_in_an_unrecognized_shape_fails_closed(self):
        # The status must end the line, as gh writes it. A line that carries
        # more after it is a shape this code has not seen, and an unrecognized
        # shape resolves to "could not tell" -- never to benign absence.
        self._fails_with("gh: failed (HTTP 404) [retrying]\n")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_the_last_verdict_wins_not_the_first(self):
        # A retrying or paginating caller produces several verdict lines. Taking
        # the first makes the classification depend on their order: "404 then
        # 500" would read as a benign absence.
        self._fails_with("gh: gone (HTTP 404)\ngh: server error (HTTP 500)\n")
        self.assertIsNone(fci.workflows("Verjson/example"))

    def test_a_three_digit_status_is_required(self):
        self._fails_with("gh: nonsense (HTTP 4)\n")
        self.assertIsNone(fci.workflows("Verjson/example"))


class RecognizerAgreement(unittest.TestCase):
    """Verjson/.github#1482. Two hand-maintained copies of one pattern is the
    condition that produced the drift, so the check is identity: the inventory
    reads the *same compiled object* and calls the *same functions* as
    `contract-version`, rather than any copy of them. Asserting equal behaviour
    on a fixture list would only pin the shapes that list happens to name."""

    def test_the_two_sweeps_share_one_recognizer_object(self):
        # `contract-version` really does read this object: it calls
        # `USES_RE.finditer` on its own module global. The inventory does not --
        # its `USES_RE` is a re-export nothing in that module consumes, so
        # asserting on it alone pins a name rather than a code path. The path
        # the inventory actually takes is `pins()` -> `references()`, so those
        # two names are what the second and third assertions pin.
        #
        # They name the *functions*. An earlier round asserted
        # `fci.references.__globals__["USES_RE"] is cv.USES_RE` instead, which
        # does not say what it looks like it says: `fci.references.__globals__`
        # is `contract_reference`'s module dict only while `fci.references` IS
        # the shared function. Define a private copy in
        # `fleet-contract-inventory.py` and the lookup reads *that* module's
        # globals, where `USES_RE` is still the shared import -- so it passes.
        # Measured: a behaviourally identical copy of `references` and `pins`
        # reintroduced there survived this assertion and the whole suite. A
        # *divergent* copy does die, but to the behavioural tests below, not to
        # this one.
        #
        # So what this guarantees is narrower than "a second copy cannot be
        # reintroduced", and exact: the inventory calls the shared functions
        # themselves, so no copy -- identical or divergent -- can sit on the
        # path either sweep takes.
        self.assertIs(fci.USES_RE, cv.USES_RE)
        self.assertIs(fci.references, contract_reference.references)
        self.assertIs(fci.pins, contract_reference.pins)

    def test_a_root_action_pin_is_a_reference_to_both_sweeps(self):
        # The divergence this issue reports: #1472 taught `contract-version` to
        # read a pathless root-action pin, and the inventory's own copy still
        # required a path segment, so the same line was a pin to one tool and
        # invisible to the other -- under-reporting in the safe-looking
        # direction.
        text = f"    uses: Verjson/.github@{A}\n"
        self.assertEqual([m.group("ref") for m in cv.USES_RE.finditer(text)], [A])
        self.assertEqual(sorted(fci.pins(text)), [(None, A)])

    def test_a_root_action_reference_resolves_against_the_root_action_file(self):
        # Making the pathless pin visible is only half of it: the inventory
        # resolves an upstream blob *at* the pinned SHA, and `path=None` is not
        # a key in any tree. GitHub resolves `owner/repo@ref` to a root action
        # file, so that is what the comparison has to use.
        self.assertEqual(
            fci.classify(None, {"action.yml": A}, {"action.yml": A}), "CURRENT")
        self.assertEqual(
            fci.classify(None, {"action.yaml": A}, {"action.yaml": B}), "DRIFTED")

    def test_a_root_action_reference_is_unknown_when_no_root_action_exists(self):
        # The hub has no root action today, so this is the live case. UNKNOWN is
        # the fail-closed answer the rest of this sweep is built on: a reference
        # whose upstream blob cannot be resolved is never CURRENT.
        self.assertEqual(fci.classify(None, {PATH: A}, {PATH: A}), "UNKNOWN")

    def test_the_inventory_reads_a_reference_per_line_not_across_one(self):
        # The second axis of divergence #1482 names. The inventory applied its
        # pattern to un-split text, where `\s*` after the key spans a newline,
        # so a bare `uses:` on one line could take the next line's hub
        # reference as its value. A `uses:` key and its value are on one line in
        # the YAML this sweep reads; a cross-line match there is not a
        # reference, it is two unrelated lines.
        text = f"    uses:\n    Verjson/.github/{PATH}@{A}\n"
        self.assertEqual(sorted(fci.pins(text)), [])


class ContractFleetReport(unittest.TestCase):
    def test_report_names_drift_and_unresolved_references(self):
        inventory = (
            "repo\tadopter_file\tupstream_path\tpinned_sha\tstatus\n"
            "verjson-cli\t.github/workflows/changelog.yml\tscripts/changelog.py\t" + A + "\tDRIFTED\n"
            "verjson-ci\t.github/workflows/node-ci.yml\t.github/workflows/node-ci.yml\t" + B + "\tUNKNOWN\n"
            "verjson-current\t.github/workflows/changelog.yml\tscripts/changelog.py\t" + A + "\tCURRENT\n"
            "\n"
            "repo\tadopter_file\theader_sha\tfile_uses_sha\theader_invariant\n"
            "verjson-cli\t.github/workflows/changelog.yml\t" + A + "\t" + B + "\tHEADER_PIN_SPLIT\n"
        )
        diagnostics = "rows=3 repos_referencing_hub=3 {\'CURRENT\': 1, \'DRIFTED\': 1, \'UNKNOWN\': 1}\nincomplete listing: Verjson/new-repo: truncated\n"

        report = reporter.render_report(inventory, diagnostics, "2026-09-22T07:00:00Z", 1)

        drift_section = report.split("## Unresolved references", 1)[0]
        self.assertIn("verjson-cli", drift_section)
        self.assertIn("## Unresolved references", report)
        self.assertIn("verjson-ci", report)
        self.assertIn("HEADER_PIN_SPLIT", report)
        self.assertIn("incomplete listing: Verjson/new-repo", report)
        self.assertIn("Inventory status: **incomplete**", report)
        self.assertNotIn("verjson-current", drift_section)

    def test_report_rejects_missing_or_malformed_inventory_tables(self):
        with self.assertRaises(ValueError):
            reporter.parse_inventory("repo\tstatus\n")

    def test_failed_inventory_without_tables_still_produces_diagnostics(self):
        report = reporter.render_report(
            "",
            "fatal: could not resolve Verjson/.github default-branch tree",
            "2026-09-22T07:00:00Z",
            1,
        )

        self.assertIn("Inventory status: **incomplete**", report)
        self.assertIn("References: 0 across 0 repositories.", report)
        self.assertIn("fatal: could not resolve Verjson/.github", report)
        self.assertIn("Inventory output unavailable:", report)

    def test_failed_inventory_bounds_rendered_diagnostics_for_valid_tables(self):
        inventory = (
            "repo\tadopter_file\tupstream_path\tpinned_sha\tstatus\n\n"
            "repo\tadopter_file\theader_sha\tfile_uses_sha\theader_invariant\n"
        )
        diagnostics = "gh: " + ("&" * (reporter.MAX_DIAGNOSTIC_CELL_CHARS * 100))

        report = reporter.render_report(
            inventory, diagnostics, "2026-09-22T07:00:00Z", 1
        )

        self.assertIn("&amp;", report)
        self.assertIn("… [truncated]", report)
        self.assertLess(len(report), 30_000)

    def test_failed_inventory_omits_excess_diagnostic_lines(self):
        inventory = (
            "repo\tadopter_file\tupstream_path\tpinned_sha\tstatus\n\n"
            "repo\tadopter_file\theader_sha\tfile_uses_sha\theader_invariant\n"
        )
        diagnostics = "\n".join("gh: diagnostic" for _ in range(reporter.MAX_DIAGNOSTIC_LINES + 5))

        report = reporter.render_report(
            inventory, diagnostics, "2026-09-22T07:00:00Z", 1
        )

        self.assertIn("Additional diagnostic lines omitted.", report)
        self.assertLess(report.count("gh: diagnostic"), reporter.MAX_DIAGNOSTIC_LINES + 1)

    def test_complete_inventory_still_rejects_malformed_tables(self):
        with self.assertRaises(ValueError):
            reporter.render_report("", "", "2026-09-22T07:00:00Z", 0)

    def test_report_escapes_untrusted_table_cells(self):
        self.assertEqual(reporter.markdown_cell("path|<script>`x`"), "path\\|&lt;script&gt;\\`x\\`")

    def test_report_workflow_is_a_private_caller_only_read_only_contract(self):
        workflow = (_root / ".github/workflows/changelog-contract-fleet-report.yml").read_text()
        self.assertIn("workflow_call:", workflow)
        self.assertNotIn("schedule:", workflow)
        self.assertNotIn("push:", workflow)
        self.assertNotIn("workflow_dispatch:", workflow)
        self.assertIn("if: github.repository == 'Verjson/verjson-agents' && github.ref == 'refs/heads/main'", workflow)
        self.assertIn("runs-on: ${{ fromJSON(vars.CI_LANE_TRUSTED || vars.CI_LANE_FALLBACK || '[\"ubuntu-24.04\"]') }}", workflow)
        self.assertIn("path: contract-source", workflow)
        self.assertIn("owner: Verjson", workflow)
        self.assertIn("permission-contents: read", workflow)
        self.assertIn("RENOVATE_COMPATIBILITY_APP_PRIVATE_KEY", workflow)
        self.assertNotIn("permission-contents: write", workflow)
        self.assertNotIn("permission-pull-requests: write", workflow)


if __name__ == "__main__":
    unittest.main(verbosity=2)
