#!/usr/bin/env bash
# `grep -q` exits on its first match. When it reads from a pipe, the producer is
# usually still writing, so its next write gets EPIPE and it dies on SIGPIPE.
# Under `set -o pipefail` — which every contract test here sets — that 141
# becomes the pipeline's status, and an assertion reports a contract violation
# that never happened (Verjson/.github#1430).
#
# It is timing-dependent, so it is invisible on an idle machine and surfaces on a
# loaded self-hosted runner: the original report measured 425 spurious failures in
# 9000 iterations of one assertion under load, and 0 in 200 unloaded. A required
# check that reddens for a reason the diff cannot cause is the ADR 0185 hazard —
# it teaches reviewers to re-run rather than read.
#
# The remedy is to drop `-q` and redirect: without it `grep` must read to EOF, so
# the producer never sees EPIPE. Same exit status, no early close.
#
# `grep -q <<<"$x"` is a here-string, not a pipe, and is unaffected.
set -uo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$here/../.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
fails=0
pass() { printf 'ok   - %s\n' "$1"; }
fail() { printf 'FAIL - %s\n' "$1"; fails=$((fails + 1)); }

# (a) The mechanism itself, deterministically. A producer that matches on its
# first line and keeps writing afterwards makes the race certain rather than
# probable, so this pins the behavior the scan below exists to prevent — without
# a stress loop whose own runtime would depend on runner load.
#
# The `-q` is assembled rather than written, so the scan in (b) does not have to
# exempt this file and thereby stop covering it.
q='q'
producer() { printf 'match\n'; sleep 0.3; printf 'tail\n'; }

status=0
( set -o pipefail; producer | grep -"$q" '^match$' ) || status=$?
if [ "$status" -eq 141 ]; then
  pass "grep -${q} kills a still-writing producer with SIGPIPE, and pipefail reports 141"
else
  fail "expected the grep -${q} pipeline to report 141; got $status (the hazard may have changed shape)"
fi

status=0
( set -o pipefail; producer | grep '^match$' >/dev/null ) || status=$?
if [ "$status" -eq 0 ]; then
  pass "the redirected form reads to EOF and reports the match honestly"
else
  fail "the redirected form reported $status instead of a clean match"
fi

# A non-match must still be a non-match: the remedy may not weaken the assertion
# it replaces.
status=0
( set -o pipefail; producer | grep '^absent$' >/dev/null ) || status=$?
if [ "$status" -eq 1 ]; then
  pass "the redirected form still reports a genuine non-match as 1"
else
  fail "the redirected form reported $status for a non-match instead of 1"
fi

# (b) No tracked shell script may reintroduce the shape. `git ls-files` is the
# boundary on purpose: it is exactly what Actions checks out, so an untracked
# scratch file cannot redden the check and a tracked one cannot hide from it.
#
# `.github/workflows` is deliberately out of scope: the same shape lives in
# generated `run:` blocks that reach ~95 adopters through the generated set, so
# changing them is a release-train change tracked separately (#1431). The frozen
# conformance regression fixtures must not be edited at all.
#
# `scripts/gen-changelog-caller.sh` is excluded for the same reason, and the
# exclusion is load-bearing rather than cosmetic: three of its occurrences are
# emitted verbatim into the generated adopter artifact
# `changelog-contract.test.sh`, so fixing them here changes generated bytes in
# every adopter and fails `required-checks-audit.test.sh` with
# `generated-contract-byte-drift`. They belong to #1431's regeneration at a new
# contract SHA, not to this flake fix.
scan="$tmp/offenders"
scanned="$tmp/scanned"
pipe_into_grep='[^|]\|[[:space:]]*(!\s*)?grep[[:space:]]+-[A-Za-z]*'"$q"
(
  cd "$repo_root" || exit 2
  git ls-files -z -- 'scripts/*.sh' 'scripts/**/*.sh' \
    | while IFS= read -r -d '' file; do
        case "$file" in
          */conformance/*|scripts/gen-changelog-caller.sh) continue ;;
        esac
        printf '%s\n' "$file" >>"$scanned"
        grep -nE "$pipe_into_grep" -- "$file" \
          | sed "s|^|$file:|" || true
      done
) >"$scan" 2>"$tmp/scan-err"

# An empty enumeration would satisfy the emptiness test below while reading
# nothing at all, so the count is part of the assertion, not a guard in front
# of it.
scanned_count="$(wc -l <"$scanned" 2>/dev/null || printf 0)"
if [ -s "$tmp/scan-err" ]; then
  fail "the scan could not run: $(head -1 "$tmp/scan-err")"
elif [ "$scanned_count" -lt 50 ]; then
  fail "the scan enumerated only $scanned_count script(s); it is not covering the tree"
elif [ -s "$scan" ]; then
  fail "$(wc -l <"$scan") pipe-fed grep -${q} site(s) reintroduced; see #1430"
  sed 's/^/       /' "$scan" >&2
else
  pass "none of the $scanned_count tracked scripts under scripts/ pipes into grep -${q}"
fi

# (c) The scan must be able to see an offender at all — a pattern that matches
# nothing would pass (b) vacuously and cover nothing.
printf 'awk "{print}" file | grep -%s pattern\n' "$q" >"$tmp/canary.sh"
if grep -nE "$pipe_into_grep" -- "$tmp/canary.sh" >/dev/null; then
  pass "the scan pattern detects the offending shape"
else
  fail "the scan pattern matches nothing, so (b) proves nothing"
fi

if [ "$fails" -ne 0 ]; then
  printf '%d test(s) failed.\n' "$fails" >&2
  exit 1
fi
