#!/usr/bin/env python3
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
CONTENT = '''# Generated by Verjson/.github; do not edit by hand.
# Regenerate from a reviewed immutable contract checkout:
# scripts/gen-changelog-caller.sh codeowners <contract-sha> > .github/CODEOWNERS
* @Verjson/devs
'''


class OwnershipError(Exception):
    pass


def check(repo_root):
    target = repo_root / '.github' / 'CODEOWNERS'
    if (repo_root / '.github').is_symlink() or target.is_symlink():
        raise OwnershipError('CODEOWNERS must be a regular repository file')
    if not target.is_file() or target.read_bytes() != CONTENT.encode():
        raise OwnershipError('missing or drifted .github/CODEOWNERS; regenerate the canonical artifact')
    if '.github' not in {entry.name for entry in repo_root.iterdir()} or \
            'CODEOWNERS' not in {entry.name for entry in (repo_root / '.github').iterdir()}:
        raise OwnershipError('canonical .github/CODEOWNERS spelling is required')
    for fallback in ('CODEOWNERS', 'docs/CODEOWNERS'):
        candidate = repo_root / fallback
        if candidate.exists() or candidate.is_symlink():
            raise OwnershipError('remove competing CODEOWNERS locations after preserving their ownership intent')


def main(arguments=None):
    parser = argparse.ArgumentParser(description='Generate or check the declared organization owner; does not verify live team access.')
    commands = parser.add_subparsers(dest='mode', required=True)
    commands.add_parser('render')
    checker = commands.add_parser('check')
    checker.add_argument('--repo-root', type=Path, default=ROOT)
    args = parser.parse_args(arguments)
    try:
        if args.mode == 'render':
            print(CONTENT, end='')
        else:
            check(args.repo_root)
    except (OwnershipError, OSError) as error:
        print(f'codeowners: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
