#!/usr/bin/env python3
"""Read-only inventory of every Verjson/.github contract reference in the fleet.

The unit of adoption is the FILE, not the repository: `Verjson/verjson-ci`
pinned `node-ci.yml` at one contract SHA and its changelog callers at another,
so any schema keyed "repo -> contract SHA" is already wrong. Every row here is
one (repo, adopter file, upstream path, pinned SHA).

Nothing here writes, and nothing here parses a generated header and then
executes what it says. Headers are read as *claims* and compared against the
file's own `uses:` pins, because a header is adopter-controlled text.

Drift is decided by comparing the upstream blob at the pinned commit with the
upstream blob on the default branch. Both sides must be a non-empty 40-hex
object id or the row is UNKNOWN, never CURRENT: `a=$(...); b=$(...); [ "$a" = "$b" ]`
reports "current" when both calls fail, which is how the previous sweep missed
the drift it was written to find.
"""
from __future__ import annotations
import base64, json, re, subprocess, sys, collections, pathlib

# Run as `python3 scripts/fleet-contract-inventory.py` and also loaded
# straight from its path by the CI-gate suite, which does not put `scripts/`
# on the path. The sibling shared recognizer must import under both.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from contract_reference import (  # noqa: E402
    ROOT_ACTION_PATHS, SHA_RE, USES_RE, pins, references)

HUB = "Verjson/.github"
REPO_LIST_LIMIT = 500
# The contents endpoint returns a whole directory in one unpaginated response
# and stops at this many entries. There is no `Link` header to follow, so the
# cap is invisible unless it is counted: a capped listing looks exactly like a
# complete one, which is the same fail-open shape as an empty listing standing
# in for a failed one.
CONTENTS_DIR_LIMIT = 1000
# Anchored to `gh`'s own one-line error form, and the LAST match is taken. An
# unanchored search over a multi-line stderr is order-dependent -- "404 then
# 500" would read as absence -- and a bare `(HTTP nnn)` could be matched out of
# prose rather than out of gh's verdict.
HTTP_STATUS_RE = re.compile(r"^gh:.*\(HTTP (?P<code>\d{3})\)\s*$", re.MULTILINE)


class _Absent:
    """"The resource is not there" -- an observation, distinct from both "here
    it is" and "the question could not be asked"."""
    __slots__ = ()


ABSENT = _Absent()
# `USES_RE`, `pins` and `references` are imported, not defined here. This sweep
# once carried its own copy of the pattern and the two drifted: a pathless
# root-action pin was a reference to `contract-version` and invisible here
# (Verjson/.github#1482). The one thing this sweep genuinely narrows -- it wants
# only *pinned* references, because it resolves an upstream tree at that SHA --
# is `pins()`, a filter over the shared recognizer rather than a second pattern.
# `# Generated by Verjson/.github scripts/gen-changelog-caller.sh <mode> <sha>`
# and `# ... generated-artifacts <sha>`.
# The trailing boundary matters: without it a 64-hex container digest in the
# same header yields its first 40 characters as a bogus claimed contract SHA.
HEADER_RE = re.compile(
    r"Verjson/\.github[^\n]*?\b(?P<sha>[0-9a-f]{40})(?![0-9a-f])",
    re.IGNORECASE)


def gh_run(*args: str) -> tuple[str | None, str]:
    """(stdout or None on failure, stderr). A hung call must not stall a sweep."""
    try:
        p = subprocess.run(["gh", *args], capture_output=True, text=True,
                           timeout=120)
    except subprocess.TimeoutExpired:
        print(f"gh timed out: {' '.join(args)}", file=sys.stderr)
        # The second slot is stderr. A timeout produced none, and inventing
        # a reason string here would be read as one.
        return None, ""
    if p.returncode != 0:
        print(f"gh failed ({p.returncode}): {' '.join(args)}: "
              f"{p.stderr.strip()[:200]}", file=sys.stderr)
        return None, p.stderr
    return p.stdout, p.stderr


def gh(*args: str) -> str | None:
    """None means the call failed."""
    return gh_run(*args)[0]


def last_status(stderr: str) -> str | None:
    """The HTTP status of gh's final verdict, or None if it stated none."""
    found = HTTP_STATUS_RE.findall(stderr)
    return found[-1] if found else None


# Directories confirmed not to exist. Reported and counted like a gap kind so
# the decision is auditable, but deliberately absent from the exit predicate:
# it is a completed observation, not a hole in the sweep.
absent_directories: list[str] = []


def gh_listing(repo: str, path: str) -> str | None | _Absent:
    """Directory text, ABSENT if it does not exist, None if the call failed.

    A 404 here is not one condition. An empty repository and a repository with
    no such directory both 404, and both are *complete observations*: there is
    nothing to inventory. Counting them as unreachable inflates the gap tally
    and exits the sweep nonzero for a benign reason -- the mirror image of the
    fail-open this tool exists to close, and how a check earns itself a mute.

    But a 404 is never *self*-explanatory, and "the enumeration listed it with
    this token" does not carry the weight it looks like it carries. GitHub
    answers 404 rather than 403 wherever admitting existence would itself leak,
    the enumeration is one snapshot taken before a sweep of hundreds of calls,
    and repository metadata and Contents are different permissions. A repo
    deleted, made private, transferred, or dropped from an App installation
    mid-sweep answers exactly like a repo that simply has no workflows.

    So absence is *confirmed*, never inferred, with a positive observation:

    - `repos/{repo}` must still read, or the repository is gone from under us
      and that is a real gap;
    - then either the repository root lists (Contents access intact, so the
      subdirectory is genuinely not there), or `commits` reports 409 (the
      repository has no commits at all).

    Anything else stays None. The cost is a few calls for the handful of
    repositories that 404, once per sweep.
    """
    out, err = gh_run("api", f"repos/{repo}/contents/{path}")
    if out is not None:
        return out
    if last_status(err) != "404":
        return None
    if gh("api", f"repos/{repo}", "--jq", ".full_name") is None:
        return None
    root, root_err = gh_run("api", f"repos/{repo}/contents/")
    if root is None:
        # The root 404s too. That is an empty repository or a lost Contents
        # grant, and only the commits endpoint tells the two apart.
        if last_status(gh_run("api", f"repos/{repo}/commits?per_page=1")[1]) != "409":
            return None
    absent_directories.append(f"{repo}:{path}")
    return ABSENT


def repos() -> list[str]:
    out = gh("repo", "list", "Verjson", "--limit", str(REPO_LIST_LIMIT), "--no-archived",
             "--json", "nameWithOwner", "--jq", ".[].nameWithOwner")
    if out is None:
        sys.exit("fatal: could not list organization repositories")
    names = sorted(filter(None, (line.strip() for line in out.splitlines())))
    if len(names) >= REPO_LIST_LIMIT:
        sys.exit(f"fatal: repository listing hit the {REPO_LIST_LIMIT} cap, so "
                 "the sweep would silently omit repositories")
    return names


_tree_cache: dict[str, dict[str, str] | None] = {}
# Paths whose blob could not be read. A completeness tool must name its gaps.
unreadable: list[str] = []
# Directories whose listing was complete-looking but capped. A different gap
# kind from an unreadable blob: the file names themselves are missing, so the
# count of unreadable paths cannot express it.
incomplete_listings: list[str] = []
# Pinned refs whose hub tree came back truncated. Same gap kind as a capped
# listing, one level up: the comparison basis is short, so every row resolved
# against it is an unsupported conclusion rather than an UNKNOWN observation.
truncated_trees: list[str] = []


def hub_tree(ref: str) -> dict[str, str] | None:
    """path -> blob sha for the whole hub tree at `ref`, or None if unresolvable."""
    if ref in _tree_cache:
        return _tree_cache[ref]
    out = gh("api", f"repos/{HUB}/git/trees/{ref}?recursive=1")
    tree = None
    if out:
        try:
            data = json.loads(out)
            if data.get("truncated"):
                truncated_trees.append(f"{HUB}@{ref} (recursive tree was truncated)")
            else:
                # Trees as well as blobs: a `uses:` can reference a composite
                # action DIRECTORY, whose identity is its subtree object id.
                # Indexing blobs only reported those references UNKNOWN.
                tree = {e["path"]: e["sha"] for e in data.get("tree", ())
                        if e.get("type") in ("blob", "tree")}
        except (json.JSONDecodeError, KeyError, TypeError, AttributeError):
            # AttributeError included deliberately: a response that parses as a
            # JSON array rather than the expected object would otherwise raise
            # out of the sweep instead of resolving to UNKNOWN.
            tree = None
    # Successes only: caching a transient failure would permanently degrade
    # every later row that shares this pin.
    if tree is not None:
        _tree_cache[ref] = tree
    return tree


def workflows(repo: str) -> dict[str, str] | None:
    """adopter workflow path -> decoded text; None if the repo was unreachable.

    An empty dict means "there is nothing to inventory": no workflow files, no
    workflows directory, or no commits at all. It must never also mean "the
    listing call failed". That conflation is the same fail-open shape `classify`
    exists to prevent, one level up: a repository whose listing 404s for a real
    reason would contribute no rows and vanish from a completeness report.

    The two are kept apart by `gh_listing`, which *confirms* an absent directory
    rather than inferring it from the 404 -- see its docstring for why a 404
    alone cannot carry that weight.
    """
    listing = gh_listing(repo, ".github/workflows")
    if listing is None:
        return None
    if isinstance(listing, _Absent):
        # Confirmed: no workflows directory, or no commits. Nothing to inventory.
        return {}
    if not listing.strip():
        return {}
    try:
        entries = json.loads(listing)
    except json.JSONDecodeError:
        return None
    if not isinstance(entries, list):
        # The docstring's contract: an empty dict is "no workflows". A listing
        # that is not an array is a listing that was not understood, which is
        # the unreachable case, not the empty one.
        return None
    if len(entries) >= CONTENTS_DIR_LIMIT:
        incomplete_listings.append(
            f"{repo}:.github/workflows (listing hit the {CONTENTS_DIR_LIMIT}-entry "
            "contents cap; read it through the git trees API)")
    files = {}
    for entry in entries:
        name = entry.get("name", "")
        if entry.get("type") != "file" or not name.endswith((".yml", ".yaml")):
            continue
        blob = gh("api", f"repos/{repo}/git/blobs/{entry['sha']}", "--jq", ".content")
        # `--jq .content` prints the four bytes `null` when the field is absent
        # or null -- the shape GitHub returns for a blob too large to inline,
        # where `encoding` is `none`. That string is valid base64 and decodes to
        # three bytes of garbage, so without this guard an unread workflow is
        # stored as real text, contributes no pins, and is reported complete.
        if not blob or blob.strip() == "null":
            unreadable.append(f"{repo}:.github/workflows/{name}")
            continue
        try:
            files[f".github/workflows/{name}"] = base64.b64decode(blob).decode("utf-8", "replace")
        except ValueError:
            # The one path into this function that did not name its own gap.
            unreadable.append(f"{repo}:.github/workflows/{name}")
            continue
    return files


def resolve_path(path: str | None, tree: dict[str, str]) -> str | None:
    """The key in `tree` a reference names, or None if it names nothing there.

    A pathless reference -- `uses: Verjson/.github@<sha>` -- names the hub's own
    root action, which GitHub resolves by trying `action.yml` then
    `action.yaml`. Returning None when neither is present is the point: the hub
    carries no root action today, so such a reference must classify UNKNOWN
    rather than be silently attributed to some other file.
    """
    if path is not None:
        return path if path in tree else None
    return next((name for name in ROOT_ACTION_PATHS if name in tree), None)


def classify(path: str | None,
             pinned_tree: dict[str, str] | None,
             main_tree: dict[str, str] | None) -> str:
    """CURRENT only on a proven equality of two resolved object ids."""
    if main_tree is None or pinned_tree is None:
        return "UNKNOWN"
    pinned_key = resolve_path(path, pinned_tree)
    main_key = resolve_path(path, main_tree)
    if pinned_key is None or main_key is None:
        return "UNKNOWN"
    a, b = pinned_tree.get(pinned_key), main_tree.get(main_key)
    if not (a and b and SHA_RE.match(a) and SHA_RE.match(b)):
        return "UNKNOWN"
    return "CURRENT" if a == b else "DRIFTED"


def main() -> int:
    main_tree = hub_tree("main")
    if main_tree is None:
        sys.exit(f"fatal: could not resolve the {HUB} default-branch tree; "
                 "every comparison would be vacuous")
    rows, header_rows, unreachable = [], [], []
    for repo in repos():
        found = workflows(repo)
        if found is None:
            unreachable.append(repo)
            print(f"... {repo} UNREACHABLE", file=sys.stderr)
            continue
        for wf_path, text in found.items():
            found_pins = set(pins(text))
            # A pathless reference has no path column to print. `<root-action>`
            # is a marker, not a file name: which of `action.yml`/`action.yaml`
            # it would resolve to depends on the tree being compared, and
            # printing one of them here would assert a file that may not exist.
            for path, sha in sorted(found_pins,
                                    key=lambda pin: (pin[0] or "", pin[1])):
                rows.append((repo, wf_path, path or "<root-action>", sha,
                             classify(path, hub_tree(sha), main_tree)))
            # Defect 3: a generated file's header SHA must equal every hub pin in
            # that same file, or a partial Renovate bump split the generated set.
            head = "\n".join(text.splitlines()[:6])
            claimed = {m.group("sha") for m in HEADER_RE.finditer(head)}
            if claimed:
                used = {sha for _, sha in found_pins}
                # `used <= claimed`: a header may legitimately record more than
                # one contract SHA (the generator plus a pinned action), but
                # every pin the file actually uses must appear in it.
                state = "CONSISTENT" if used and used <= claimed else (
                    "NO_PINS" if not used else "HEADER_PIN_SPLIT")
                header_rows.append((repo, wf_path, ",".join(sorted(claimed)),
                                    ",".join(sorted(used)) or "-", state))
        print(f"... {repo}", file=sys.stderr)

    print("repo\tadopter_file\tupstream_path\tpinned_sha\tstatus")
    for r in rows:
        print("\t".join(r))
    print()
    print("repo\tadopter_file\theader_sha\tfile_uses_sha\theader_invariant")
    for r in header_rows:
        print("\t".join(r))

    tally = collections.Counter(r[4] for r in rows)
    repos_with_rows = {r[0] for r in rows}
    drifted_repos = {r[0] for r in rows if r[4] == "DRIFTED"}
    skewed = {r[0] for r in rows
              if len({x[3] for x in rows if x[0] == r[0]}) > 1}
    print(f"\nrows={len(rows)} repos_referencing_hub={len(repos_with_rows)} "
          f"{dict(tally)} drifted_repos={len(drifted_repos)} "
          f"repos_with_intra_repo_pin_skew={len(skewed)} "
          f"unreachable_repos={len(unreachable)} "
          f"unreadable_files={len(unreadable)} "
          f"incomplete_listings={len(incomplete_listings)} "
          f"truncated_trees={len(truncated_trees)} "
          f"absent_directories={len(absent_directories)}", file=sys.stderr)
    if unreachable:
        print("unreachable: " + " ".join(unreachable), file=sys.stderr)
    if unreadable:
        print("unreadable: " + " ".join(unreadable), file=sys.stderr)
    # Counted and named, but not a gap: each of these was confirmed absent
    # rather than assumed to be, and the confirmation is the auditable part.
    if absent_directories:
        print("absent (confirmed, not a gap): "
              + " ".join(absent_directories), file=sys.stderr)
    # One per line: a capped-listing gap carries spaces, so a space-joined list
    # would no longer be one token per gap.
    for gap in incomplete_listings:
        print("incomplete listing: " + gap, file=sys.stderr)
    for gap in truncated_trees:
        print("truncated tree: " + gap, file=sys.stderr)
    # A sweep that lost its token halfway through has a truncated inventory.
    # Exiting 0 on it would report incompleteness as completeness.
    return 1 if (unreachable or unreadable or incomplete_listings
                 or truncated_trees) else 0


if __name__ == "__main__":
    raise SystemExit(main())
