#!/usr/bin/env python3
"""Read-only inventory of every Verjson/.github contract reference in the fleet.

The unit of adoption is the FILE, not the repository: `Verjson/verjson-ci`
pinned `node-ci.yml` at one contract SHA and its changelog callers at another,
so any schema keyed "repo -> contract SHA" is already wrong. Every row here is
one (repo, adopter file, upstream path, pinned SHA).

Nothing here writes, and nothing here parses a generated header and then
executes what it says. Headers are read as *claims* and compared against the
file's own `uses:` pins, because a header is adopter-controlled text.

Drift is decided by comparing the upstream blob at the pinned commit with the
upstream blob on the default branch. Both sides must be a non-empty 40-hex
object id or the row is UNKNOWN, never CURRENT: `a=$(...); b=$(...); [ "$a" = "$b" ]`
reports "current" when both calls fail, which is how the previous sweep missed
the drift it was written to find.
"""
from __future__ import annotations
import base64, json, re, subprocess, sys, collections

HUB = "Verjson/.github"
REPO_LIST_LIMIT = 500
# The contents endpoint returns a whole directory in one unpaginated response
# and stops at this many entries. There is no `Link` header to follow, so the
# cap is invisible unless it is counted: a capped listing looks exactly like a
# complete one, which is the same fail-open shape as an empty listing standing
# in for a failed one.
CONTENTS_DIR_LIMIT = 1000
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
# GitHub resolves owner/repo case-insensitively, so a lowercase adopter
# reference is a real reference; a completeness sweep must not drop it.
USES_RE = re.compile(
    r"uses:\s*Verjson/\.github/(?P<path>[^@\s]+)@(?P<sha>[0-9a-f]{40})(?![0-9a-f])",
    re.IGNORECASE)
# `# Generated by Verjson/.github scripts/gen-changelog-caller.sh <mode> <sha>`
# and `# ... generated-artifacts <sha>`.
# The trailing boundary matters: without it a 64-hex container digest in the
# same header yields its first 40 characters as a bogus claimed contract SHA.
HEADER_RE = re.compile(
    r"Verjson/\.github[^\n]*?\b(?P<sha>[0-9a-f]{40})(?![0-9a-f])",
    re.IGNORECASE)


def gh(*args: str) -> str | None:
    """None means the call failed. A hung call must not stall a ~95-repo sweep."""
    try:
        p = subprocess.run(["gh", *args], capture_output=True, text=True,
                           timeout=120)
    except subprocess.TimeoutExpired:
        print(f"gh timed out: {' '.join(args)}", file=sys.stderr)
        return None
    if p.returncode != 0:
        print(f"gh failed ({p.returncode}): {' '.join(args)}: "
              f"{p.stderr.strip()[:200]}", file=sys.stderr)
        return None
    return p.stdout


def repos() -> list[str]:
    out = gh("repo", "list", "Verjson", "--limit", str(REPO_LIST_LIMIT), "--no-archived",
             "--json", "nameWithOwner", "--jq", ".[].nameWithOwner")
    if out is None:
        sys.exit("fatal: could not list organization repositories")
    names = sorted(filter(None, (line.strip() for line in out.splitlines())))
    if len(names) >= REPO_LIST_LIMIT:
        sys.exit(f"fatal: repository listing hit the {REPO_LIST_LIMIT} cap, so "
                 "the sweep would silently omit repositories")
    return names


_tree_cache: dict[str, dict[str, str] | None] = {}
# Paths whose blob could not be read. A completeness tool must name its gaps.
unreadable: list[str] = []
# Directories whose listing was complete-looking but capped. A different gap
# kind from an unreadable blob: the file names themselves are missing, so the
# count of unreadable paths cannot express it.
incomplete_listings: list[str] = []
# Pinned refs whose hub tree came back truncated. Same gap kind as a capped
# listing, one level up: the comparison basis is short, so every row resolved
# against it is an unsupported conclusion rather than an UNKNOWN observation.
truncated_trees: list[str] = []


def hub_tree(ref: str) -> dict[str, str] | None:
    """path -> blob sha for the whole hub tree at `ref`, or None if unresolvable."""
    if ref in _tree_cache:
        return _tree_cache[ref]
    out = gh("api", f"repos/{HUB}/git/trees/{ref}?recursive=1")
    tree = None
    if out:
        try:
            data = json.loads(out)
            if data.get("truncated"):
                truncated_trees.append(f"{HUB}@{ref} (recursive tree was truncated)")
            else:
                # Trees as well as blobs: a `uses:` can reference a composite
                # action DIRECTORY, whose identity is its subtree object id.
                # Indexing blobs only reported those references UNKNOWN.
                tree = {e["path"]: e["sha"] for e in data.get("tree", ())
                        if e.get("type") in ("blob", "tree")}
        except (json.JSONDecodeError, KeyError, TypeError, AttributeError):
            # AttributeError included deliberately: a response that parses as a
            # JSON array rather than the expected object would otherwise raise
            # out of the sweep instead of resolving to UNKNOWN.
            tree = None
    # Successes only: caching a transient failure would permanently degrade
    # every later row that shares this pin.
    if tree is not None:
        _tree_cache[ref] = tree
    return tree


def workflows(repo: str) -> dict[str, str] | None:
    """adopter workflow path -> decoded text; None if the repo was unreachable.

    An empty dict means "no workflows"; it must never also mean "the listing
    call failed". That conflation is the same fail-open shape `classify` exists
    to prevent, one level up: a repository whose listing 404s for a real reason
    would contribute no rows and vanish from a completeness report.
    """
    listing = gh("api", f"repos/{repo}/contents/.github/workflows")
    if listing is None:
        return None
    if not listing.strip():
        return {}
    try:
        entries = json.loads(listing)
    except json.JSONDecodeError:
        return None
    if not isinstance(entries, list):
        # The docstring's contract: an empty dict is "no workflows". A listing
        # that is not an array is a listing that was not understood, which is
        # the unreachable case, not the empty one.
        return None
    if len(entries) >= CONTENTS_DIR_LIMIT:
        incomplete_listings.append(
            f"{repo}:.github/workflows (listing hit the {CONTENTS_DIR_LIMIT}-entry "
            "contents cap; read it through the git trees API)")
    files = {}
    for entry in entries:
        name = entry.get("name", "")
        if entry.get("type") != "file" or not name.endswith((".yml", ".yaml")):
            continue
        blob = gh("api", f"repos/{repo}/git/blobs/{entry['sha']}", "--jq", ".content")
        # `--jq .content` prints the four bytes `null` when the field is absent
        # or null -- the shape GitHub returns for a blob too large to inline,
        # where `encoding` is `none`. That string is valid base64 and decodes to
        # three bytes of garbage, so without this guard an unread workflow is
        # stored as real text, contributes no pins, and is reported complete.
        if not blob or blob.strip() == "null":
            unreadable.append(f"{repo}:.github/workflows/{name}")
            continue
        try:
            files[f".github/workflows/{name}"] = base64.b64decode(blob).decode("utf-8", "replace")
        except ValueError:
            # The one path into this function that did not name its own gap.
            unreadable.append(f"{repo}:.github/workflows/{name}")
            continue
    return files


def classify(path: str,
             pinned_tree: dict[str, str] | None,
             main_tree: dict[str, str] | None) -> str:
    """CURRENT only on a proven equality of two resolved object ids."""
    if main_tree is None or pinned_tree is None:
        return "UNKNOWN"
    a, b = pinned_tree.get(path), main_tree.get(path)
    if not (a and b and SHA_RE.match(a) and SHA_RE.match(b)):
        return "UNKNOWN"
    return "CURRENT" if a == b else "DRIFTED"


def main() -> int:
    main_tree = hub_tree("main")
    if main_tree is None:
        sys.exit(f"fatal: could not resolve the {HUB} default-branch tree; "
                 "every comparison would be vacuous")
    rows, header_rows, unreachable = [], [], []
    for repo in repos():
        found = workflows(repo)
        if found is None:
            unreachable.append(repo)
            print(f"... {repo} UNREACHABLE", file=sys.stderr)
            continue
        for wf_path, text in found.items():
            pins = {(m.group("path"), m.group("sha")) for m in USES_RE.finditer(text)}
            for path, sha in sorted(pins):
                rows.append((repo, wf_path, path, sha,
                             classify(path, hub_tree(sha), main_tree)))
            # Defect 3: a generated file's header SHA must equal every hub pin in
            # that same file, or a partial Renovate bump split the generated set.
            head = "\n".join(text.splitlines()[:6])
            claimed = {m.group("sha") for m in HEADER_RE.finditer(head)}
            if claimed:
                used = {sha for _, sha in pins}
                # `used <= claimed`: a header may legitimately record more than
                # one contract SHA (the generator plus a pinned action), but
                # every pin the file actually uses must appear in it.
                state = "CONSISTENT" if used and used <= claimed else (
                    "NO_PINS" if not used else "HEADER_PIN_SPLIT")
                header_rows.append((repo, wf_path, ",".join(sorted(claimed)),
                                    ",".join(sorted(used)) or "-", state))
        print(f"... {repo}", file=sys.stderr)

    print("repo\tadopter_file\tupstream_path\tpinned_sha\tstatus")
    for r in rows:
        print("\t".join(r))
    print()
    print("repo\tadopter_file\theader_sha\tfile_uses_sha\theader_invariant")
    for r in header_rows:
        print("\t".join(r))

    tally = collections.Counter(r[4] for r in rows)
    repos_with_rows = {r[0] for r in rows}
    drifted_repos = {r[0] for r in rows if r[4] == "DRIFTED"}
    skewed = {r[0] for r in rows
              if len({x[3] for x in rows if x[0] == r[0]}) > 1}
    print(f"\nrows={len(rows)} repos_referencing_hub={len(repos_with_rows)} "
          f"{dict(tally)} drifted_repos={len(drifted_repos)} "
          f"repos_with_intra_repo_pin_skew={len(skewed)} "
          f"unreachable_repos={len(unreachable)} "
          f"unreadable_files={len(unreadable)} "
          f"incomplete_listings={len(incomplete_listings)} "
          f"truncated_trees={len(truncated_trees)}", file=sys.stderr)
    if unreachable:
        print("unreachable: " + " ".join(unreachable), file=sys.stderr)
    if unreadable:
        print("unreadable: " + " ".join(unreadable), file=sys.stderr)
    # One per line: a capped-listing gap carries spaces, so a space-joined list
    # would no longer be one token per gap.
    for gap in incomplete_listings:
        print("incomplete listing: " + gap, file=sys.stderr)
    for gap in truncated_trees:
        print("truncated tree: " + gap, file=sys.stderr)
    # A sweep that lost its token halfway through has a truncated inventory.
    # Exiting 0 on it would report incompleteness as completeness.
    return 1 if (unreachable or unreadable or incomplete_listings
                 or truncated_trees) else 0


if __name__ == "__main__":
    raise SystemExit(main())
