#!/usr/bin/env python3
"""Read-only inventory of every Verjson/.github contract reference in the fleet.

The unit of adoption is the FILE, not the repository: `Verjson/verjson-ci`
pinned `node-ci.yml` at one contract SHA and its changelog callers at another,
so any schema keyed "repo -> contract SHA" is already wrong. Every row here is
one (repo, adopter file, upstream path, pinned SHA).

Nothing here writes, and nothing here parses a generated header and then
executes what it says. Headers are read as *claims* and compared against the
file's own `uses:` pins, because a header is adopter-controlled text.

Drift is decided by comparing the upstream blob at the pinned commit with the
upstream blob on the default branch. Both sides must be a non-empty 40-hex
object id or the row is UNKNOWN, never CURRENT: `a=$(...); b=$(...); [ "$a" = "$b" ]`
reports "current" when both calls fail, which is how the previous sweep missed
the drift it was written to find.
"""
from __future__ import annotations
import base64, json, re, subprocess, sys, collections

HUB = "Verjson/.github"
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
USES_RE = re.compile(
    r"uses:\s*Verjson/\.github/(?P<path>[^@\s]+)@(?P<sha>[0-9a-f]{40})")
# `# Generated by Verjson/.github scripts/gen-changelog-caller.sh <mode> <sha>`
# and `# ... generated-artifacts <sha>`.
HEADER_RE = re.compile(r"Verjson/\.github[^\n]*?\b(?P<sha>[0-9a-f]{40})")


def gh(*args: str) -> str | None:
    p = subprocess.run(["gh", *args], capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else None


def repos() -> list[str]:
    out = gh("repo", "list", "Verjson", "--limit", "500", "--no-archived",
             "--json", "nameWithOwner", "--jq", ".[].nameWithOwner")
    if out is None:
        sys.exit("fatal: could not list organization repositories")
    return sorted(filter(None, (line.strip() for line in out.splitlines())))


_tree_cache: dict[str, dict[str, str] | None] = {}


def hub_tree(ref: str) -> dict[str, str] | None:
    """path -> blob sha for the whole hub tree at `ref`, or None if unresolvable."""
    if ref in _tree_cache:
        return _tree_cache[ref]
    out = gh("api", f"repos/{HUB}/git/trees/{ref}?recursive=1")
    tree = None
    if out:
        try:
            data = json.loads(out)
            if not data.get("truncated"):
                # Trees as well as blobs: a `uses:` can reference a composite
                # action DIRECTORY, whose identity is its subtree object id.
                # Indexing blobs only reported those references UNKNOWN.
                tree = {e["path"]: e["sha"] for e in data.get("tree", ())
                        if e.get("type") in ("blob", "tree")}
        except (json.JSONDecodeError, KeyError, TypeError):
            tree = None
    _tree_cache[ref] = tree
    return tree


def workflows(repo: str) -> dict[str, str]:
    """adopter workflow path -> decoded text."""
    listing = gh("api", f"repos/{repo}/contents/.github/workflows")
    if not listing:
        return {}
    try:
        entries = json.loads(listing)
    except json.JSONDecodeError:
        return {}
    files = {}
    for entry in entries:
        name = entry.get("name", "")
        if entry.get("type") != "file" or not name.endswith((".yml", ".yaml")):
            continue
        blob = gh("api", f"repos/{repo}/git/blobs/{entry['sha']}", "--jq", ".content")
        if not blob:
            continue
        try:
            files[f".github/workflows/{name}"] = base64.b64decode(blob).decode("utf-8", "replace")
        except ValueError:
            continue
    return files


def classify(path: str,
             pinned_tree: dict[str, str] | None,
             main_tree: dict[str, str] | None) -> str:
    """CURRENT only on a proven equality of two resolved object ids."""
    if main_tree is None or pinned_tree is None:
        return "UNKNOWN"
    a, b = pinned_tree.get(path), main_tree.get(path)
    if not (a and b and SHA_RE.match(a) and SHA_RE.match(b)):
        return "UNKNOWN"
    return "CURRENT" if a == b else "DRIFTED"


def main() -> int:
    main_tree = hub_tree("main")
    if main_tree is None:
        sys.exit(f"fatal: could not resolve the {HUB} default-branch tree; "
                 "every comparison would be vacuous")
    rows, header_rows = [], []
    for repo in repos():
        for wf_path, text in workflows(repo).items():
            pins = {(m.group("path"), m.group("sha")) for m in USES_RE.finditer(text)}
            for path, sha in sorted(pins):
                rows.append((repo, wf_path, path, sha,
                             classify(path, hub_tree(sha), main_tree)))
            # Defect 3: a generated file's header SHA must equal every hub pin in
            # that same file, or a partial Renovate bump split the generated set.
            head = "\n".join(text.splitlines()[:6])
            claimed = {m.group("sha") for m in HEADER_RE.finditer(head)}
            if claimed:
                used = {sha for _, sha in pins}
                state = "CONSISTENT" if used and used <= claimed else (
                    "NO_PINS" if not used else "HEADER_PIN_SPLIT")
                header_rows.append((repo, wf_path, ",".join(sorted(claimed)),
                                    ",".join(sorted(used)) or "-", state))
        print(f"... {repo}", file=sys.stderr)

    print("repo\tadopter_file\tupstream_path\tpinned_sha\tstatus")
    for r in rows:
        print("\t".join(r))
    print()
    print("repo\tadopter_file\theader_sha\tfile_uses_sha\theader_invariant")
    for r in header_rows:
        print("\t".join(r))

    tally = collections.Counter(r[4] for r in rows)
    repos_with_rows = {r[0] for r in rows}
    drifted_repos = {r[0] for r in rows if r[4] == "DRIFTED"}
    skewed = {r[0] for r in rows
              if len({x[3] for x in rows if x[0] == r[0]}) > 1}
    print(f"\nrows={len(rows)} repos_referencing_hub={len(repos_with_rows)} "
          f"{dict(tally)} drifted_repos={len(drifted_repos)} "
          f"repos_with_intra_repo_pin_skew={len(skewed)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
