#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; kind="${1:?kind}"; ref="${2:?40-hex contract ref}"; config="${3:-container-candidate.json}"
[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || exit 1
[[ "$config" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*\.json$ && "/$config/" != *"/../"* ]] || { echo "config path must be a repository-relative JSON path" >&2; exit 2; }
case "$kind" in
workflow) cat <<EOF
# Generated by Verjson/.github/scripts/gen-container-release.sh; do not edit.
name: container release
on:
  workflow_dispatch:
    inputs:
      version: {required: true, type: string}
      candidate-manifest: {required: true, type: string}
jobs:
  release:
    uses: Verjson/.github/.github/workflows/container-release.yml@$ref
    with:
      version: \${{ inputs.version }}
      candidate-manifest: \${{ inputs.candidate-manifest }}
      config-path: $config
      contract-ref: $ref
    secrets:
      release-token: \${{ secrets.VERJSON_RELEASE_TOKEN }}
EOF
;;
validator) git -C "$root" show "$ref:scripts/container_release_promotion.py" ;;
manifest-validator) git -C "$root" show "$ref:scripts/container_release_manifest.py" ;;
artifact-extractor) git -C "$root" show "$ref:scripts/container_artifact_extract.py" ;;
contract-test)
promotion_digest="$(git -C "$root" show "$ref:scripts/container_release_promotion.py" | sha256sum | cut -d' ' -f1)"
manifest_digest="$(git -C "$root" show "$ref:scripts/container_release_manifest.py" | sha256sum | cut -d' ' -f1)"
extractor_digest="$(git -C "$root" show "$ref:scripts/container_artifact_extract.py" | sha256sum | cut -d' ' -f1)"
cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
ref='$ref'
grep -Fq "container-release.yml@\$ref" .github/workflows/container-release.yml
grep -Fq "contract-ref: \$ref" .github/workflows/container-release.yml
grep -q "workflow_dispatch:" .github/workflows/container-release.yml
! grep -Eq '^  (push|pull_request):' .github/workflows/container-release.yml
grep -q 'VERJSON_RELEASE_TOKEN' .github/workflows/container-release.yml
test -f scripts/container_release_promotion.py
test -f scripts/container_release_manifest.py
test -f scripts/container_artifact_extract.py
printf '%s  %s\n' '$promotion_digest' scripts/container_release_promotion.py | sha256sum --check --strict
printf '%s  %s\n' '$manifest_digest' scripts/container_release_manifest.py | sha256sum --check --strict
printf '%s  %s\n' '$extractor_digest' scripts/container_artifact_extract.py | sha256sum --check --strict
grep -q 'Generated by Verjson/.github/scripts/gen-container-release.sh' .github/workflows/container-release.yml
echo 'container release contract passed'
EOF
;; *) exit 2;; esac
