#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
kind="${1:?kind}"
ref="${2:?40-hex contract ref}"
config="${3:-container-deployment.json}"

[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || { echo "contract ref must be 40 lowercase hex" >&2; exit 1; }
[[ "$config" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*\.json$ && "/$config/" != *"/../"* ]] || {
  echo "config path must be a repository-relative JSON path" >&2
  exit 2
}

emit_python() {
  local source="$1"
  cat <<EOF
#!/usr/bin/env python3
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: $ref
# Source: Verjson/.github/$source@$ref
EOF
  git -C "$root" show "$ref:$source" | sed '1{/^#!\/usr\/bin\/env python3$/d;}'
}

emit_review_workflow() {
  local review_kind="$1"
  local review_input="review-id"
  [[ "$review_kind" == ai ]] && review_input="source-check-run-id"
  cat <<EOF
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
name: runner deployment $review_kind review producer
on:
  workflow_dispatch:
    inputs:
      pull-request: {required: true, type: number}
      $review_input: {required: true, type: number}
permissions:
  actions: write
  checks: read
  contents: read
  pull-requests: read
jobs:
  produce:
    uses: Verjson/.github/.github/workflows/container-deployment-review-producer.yml@$ref
    with:
      kind: $review_kind
      pull-request: \${{ inputs.pull-request }}
      $review_input: \${{ inputs.$review_input }}
      config-path: $config
EOF
}

case "$kind" in
  workflow)
    cat <<EOF
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
name: protected runner deployment
on:
  workflow_dispatch:
    inputs:
      manifest-identity:
        description: Immutable canonical release-manifest asset digest
        required: true
        type: string
      fleet-selector:
        description: Reviewed consumer fleet selector
        required: true
        type: string
      action:
        description: Deploy or independently approved rollback
        required: true
        type: choice
        options: [deploy, rollback]
      rollback-receipt:
        description: Canonical digest of the retained failed or interrupted receipt
        required: false
        type: string
      dry-run:
        description: Produce exact host plan without external mutation
        required: true
        default: true
        type: boolean
permissions:
  actions: read
  attestations: read
  checks: read
  contents: read
  packages: read
  pull-requests: read
jobs:
  deploy:
    uses: Verjson/.github/.github/workflows/container-deployment.yml@$ref
    with:
      manifest-identity: \${{ inputs.manifest-identity }}
      fleet-selector: \${{ inputs.fleet-selector }}
      action: \${{ inputs.action }}
      rollback-receipt: \${{ inputs.rollback-receipt }}
      dry-run: \${{ inputs.dry-run }}
      config-path: $config
      contract-ref: $ref
EOF
    ;;
  code-review-workflow)
    emit_review_workflow code
    ;;
  security-review-workflow)
    emit_review_workflow security
    ;;
  ai-review-workflow)
    emit_review_workflow ai
    ;;
  review-producer-workflow)
    git -C "$root" show "$ref:.github/workflows/container-deployment-review-producer.yml"
    ;;
  review-producer)
    emit_python scripts/container_deployment_review_producer.py
    ;;
  transport)
    emit_python scripts/container_deployment_transport.py
    ;;
  controller)
    emit_python scripts/container_deployment_controller.py
    ;;
  preflight)
    emit_python scripts/container_deployment_preflight.py
    ;;
  receipt-schema)
    git -C "$root" show \
      "$ref:docs/decisions/0078-container-release-and-runner-deployment-contract/deployment-receipt.schema.json"
    ;;
  contract-test)
    workflow_digest="$("$0" workflow "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    transport_digest="$("$0" transport "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    controller_digest="$("$0" controller "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    preflight_digest="$("$0" preflight "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    schema_digest="$("$0" receipt-schema "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    code_review_digest="$("$0" code-review-workflow "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    security_review_digest="$("$0" security-review-workflow "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    ai_review_digest="$("$0" ai-review-workflow "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    review_workflow_digest="$("$0" review-producer-workflow "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    review_producer_digest="$("$0" review-producer "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    cat <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: $ref
#
# Every assertion reports what it expected and what it observed. A required
# contract test that exits 1 printing nothing forces an adopter to bisect this
# generated file by hand to find the unmet precondition
# (Verjson/verjson-git-runners#207). The reporting below only adds diagnostics:
# no assertion is relaxed, and the ERR trap re-exits with the original status so
# any assertion added later still fails closed, named by line.

contract_fail() {
  printf 'container-deployment contract FAILED: %s\\n' "\$*" >&2
  exit 1
}
trap 'contract_status=\$?; printf "container-deployment contract FAILED: assertion at %s line %s exited %s\\n" "\$0" "\$LINENO" "\$contract_status" >&2; exit "\$contract_status"' ERR

assert_digest() {
  local path="\$1" expected="\$2" observed
  [ -f "\$path" ] || contract_fail "\$path is missing (pinned sha256 \$expected)"
  observed="\$(sha256sum "\$path" | cut -d' ' -f1)"
  [ "\$observed" = "\$expected" ] || contract_fail \\
    "\$path drifted from contract $ref: expected sha256 \$expected, observed sha256 \$observed"
}

assert_contains() {
  local path="\$1" needle="\$2"
  [ -f "\$path" ] || contract_fail "\$path is missing (expected to contain: \$needle)"
  grep -qF -- "\$needle" "\$path" || contract_fail \\
    "\$path does not contain the required pinned text: \$needle"
}

assert_digest .github/workflows/container-deployment.yml $workflow_digest
assert_digest scripts/container_deployment_controller.py $controller_digest
assert_digest scripts/container_deployment_transport.py $transport_digest
assert_digest scripts/container_deployment_preflight.py $preflight_digest
assert_digest scripts/deployment-receipt.schema.json $schema_digest
assert_digest .github/workflows/container-deployment-code-review.yml $code_review_digest
assert_digest .github/workflows/container-deployment-security-review.yml $security_review_digest
assert_digest .github/workflows/container-deployment-ai-review.yml $ai_review_digest
assert_digest .github/workflows/container-deployment-review-producer.yml $review_workflow_digest
assert_digest scripts/container_deployment_review_producer.py $review_producer_digest

[ -f "$config" ] || contract_fail "deployment config $config is missing"
jq -e '
  .schemaVersion == 1 and
  (.reviewAuthority | keys | sort == ["ai", "code", "security"]) and
  ([.reviewAuthority[].installationId] | all(type == "number" and . > 0)) and
  (.reviewAuthority.ai.sourceAppId | type == "number" and . > 0) and
  (.reviewAuthority.ai.sourceCheckName | type == "string" and length > 0) and
  .cliCommand == ["verjson-cloud"] and
  (.evidenceCommand | length == 2) and
  (.probeCommand | length == 2) and
  (.fleets | type == "object" and length > 0)
' "$config" >/dev/null || contract_fail "\$(
  jq -r '
    [
      (if .schemaVersion == 1 then empty else "schemaVersion: expected 1, observed \\(.schemaVersion | tojson)" end),
      (if (.reviewAuthority | keys | sort == ["ai", "code", "security"]) then empty else "reviewAuthority: expected keys [ai, code, security], observed \\(.reviewAuthority | keys? // null | tojson)" end),
      (if ([.reviewAuthority[]?.installationId] | all(type == "number" and . > 0)) then empty else "reviewAuthority[].installationId: expected positive numbers, observed \\([.reviewAuthority[]?.installationId] | tojson)" end),
      (if (.reviewAuthority.ai.sourceAppId | type == "number" and . > 0) then empty else "reviewAuthority.ai.sourceAppId: expected a positive number, observed \\(.reviewAuthority.ai.sourceAppId | tojson)" end),
      (if (.reviewAuthority.ai.sourceCheckName | type == "string" and length > 0) then empty else "reviewAuthority.ai.sourceCheckName: expected a non-empty string, observed \\(.reviewAuthority.ai.sourceCheckName | tojson)" end),
      (if .cliCommand == ["verjson-cloud"] then empty else "cliCommand: expected [\\"verjson-cloud\\"], observed \\(.cliCommand | tojson)" end),
      (if (.evidenceCommand | length == 2) then empty else "evidenceCommand: expected 2 elements, observed \\(.evidenceCommand | tojson)" end),
      (if (.probeCommand | length == 2) then empty else "probeCommand: expected 2 elements, observed \\(.probeCommand | tojson)" end),
      (if (.fleets | type == "object" and length > 0) then empty else "fleets: expected a non-empty object, observed \\(.fleets | tojson)" end)
    ] | join("; ")
  ' "$config" 2>/dev/null || echo "$config is not readable JSON"
)"
while IFS= read -r adapter; do
  [ -f "\$adapter" ] || contract_fail \\
    "$config names adapter \$adapter, which is not a regular file in this repository"
  [ ! -L "\$adapter" ] || contract_fail \\
    "$config names adapter \$adapter, which is a symlink; the contract requires a real file"
done < <(jq -r '.evidenceCommand[1], .probeCommand[1]' "$config")
assert_contains .github/workflows/container-deployment.yml 'container-deployment.yml@$ref'
assert_contains .github/workflows/container-deployment.yml 'contract-ref: $ref'
if forbidden="\$(grep -En 'secrets:|environment:|RUNNER_DEPLOY_TOKEN|DIGITALOCEAN_RUNNER_FLEET_TOKEN|GH_RUNNER_REGISTRATION_APP_PRIVATE_KEY|:latest|:stable' \\
  .github/workflows/container-deployment.yml)"; then
  contract_fail "\$(printf '.github/workflows/container-deployment.yml must not name secrets, environments, or mutable tags; observed:\\n%s' "\$forbidden")"
fi
python3 -m py_compile scripts/container_deployment_controller.py scripts/container_deployment_preflight.py scripts/container_deployment_transport.py \\
  || contract_fail "a pinned deployment python module failed to compile (see the traceback above)"
python3 -m json.tool scripts/deployment-receipt.schema.json >/dev/null \\
  || contract_fail "scripts/deployment-receipt.schema.json is not valid JSON (see the error above)"
python3 - .github/workflows/container-deployment.yml <<'PY'
import sys
import yaml

with open(sys.argv[1], encoding="utf-8") as stream:
    workflow = yaml.safe_load(stream)
trigger = workflow.get("on", workflow.get(True))
assert set(trigger) == {"workflow_dispatch"}, (
    f"{sys.argv[1]}: expected exactly the workflow_dispatch trigger, observed {sorted(trigger)}"
)
job = workflow["jobs"]["deploy"]
assert set(job) == {"uses", "with"}, (
    f"{sys.argv[1]}: deploy job expected exactly the keys ['uses', 'with'], observed {sorted(job)}"
)
assert job["uses"].startswith("Verjson/.github/.github/workflows/container-deployment.yml@"), (
    f"{sys.argv[1]}: deploy job expected to call the canonical container-deployment.yml, observed {job['uses']!r}"
)
observed_permissions = set(workflow["permissions"])
expected_permissions = {
    "actions", "attestations", "checks", "contents", "packages", "pull-requests"
}
assert observed_permissions == expected_permissions, (
    f"{sys.argv[1]}: expected permissions {sorted(expected_permissions)}, "
    f"observed {sorted(observed_permissions)}"
)
PY
EOF
    ;;
  *)
    echo "kind must be workflow, code-review-workflow, security-review-workflow, ai-review-workflow, review-producer-workflow, review-producer, controller, preflight, receipt-schema, or contract-test" >&2
    exit 2
    ;;
esac
