#!/usr/bin/env bash
# Generate a consumer's changelog contract adoption files.
#
# Generated, not hand-written, because the parts must agree on one commit and
# nothing fails loudly when they don't: the renderer keeps rendering, the
# workflow keeps validating, and local output silently stops predicting CI.
# Hand-writing this three times already produced three shapes.
#
# The contract test is generated for a second reason (#309). It was the last
# hand-copied surface, so each consumer copied it from whichever repository had
# migrated most recently — and inherited that repository's assumptions about its
# own state. The shape in circulation asserted the pre-release state (fragments
# by name, no CHANGELOG.md, no released history), which the first release
# destroys by design, so it was green until a release and red forever after.
#
# Usage:
#   scripts/gen-changelog-caller.sh workflow      <sha> > .github/workflows/changelog.yml
#   scripts/gen-changelog-caller.sh renderer      <sha> > scripts/render-next.sh
#   scripts/gen-changelog-caller.sh contract-test <sha> > scripts/changelog-contract.test.sh
#
# Consumers pin an immutable commit (docs/changelog/README.md) rather than a
# branch: the contract defines their release history's shape, so it must not
# move under them between a local render and the CI run that gates the PR.
set -euo pipefail

usage() {
  echo "usage: $(basename "$0") {workflow|renderer|contract-test} <40-hex-commit>" >&2
  exit 2
}

[ "$#" -eq 2 ] || usage
mode="$1"
ref="$2"

# Strictly validated, not merely quoted. Both outputs interpolate this value —
# one into YAML, one into a shell assignment — so anything other than a bare
# commit is an injection vector. The sibling gen-privileged-merge-caller.sh
# documents a live instance of exactly that class.
[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || {
  echo "$(basename "$0"): ref must be a 40-character lowercase commit SHA" >&2
  exit 2
}

emit_workflow() {
  cat <<EOF
name: changelog

on:
  pull_request:

permissions:
  contents: read

jobs:
  changelog:
    uses: Verjson/.github/.github/workflows/changelog-validate.yml@${ref}
    with:
      contract_ref: ${ref}
EOF
}

# Emitted into both generated scripts from one function, so the path they resolve
# the pinned contract at is equal by construction rather than by coincidence.
# #304 was the coincidence: the copied contract test set CHANGELOG_CONTRACT_PATH
# that the renderer had stopped reading, and stayed green only because the
# default it computed independently happened to be byte-identical. There is
# deliberately no override — a variable that redirects execution to an arbitrary
# file is the vendored-copy drift ADR 0038 exists to close.
emit_contract_resolution() {
  cat <<EOF

root="\$(cd "\$(dirname "\$0")/.." && pwd)"
cache_dir="\${XDG_CACHE_HOME:-\$HOME/.cache}/verjson-changelog/\$CONTRACT_REF"
contract="\$cache_dir/changelog.py"

# Addressed by commit, so a cached copy cannot go stale: a new pin is a new path.
if [ ! -f "\$contract" ]; then
  mkdir -p "\$cache_dir"
  url="https://raw.githubusercontent.com/Verjson/.github/\$CONTRACT_REF/scripts/changelog.py"
  # mktemp, not a fixed name: two concurrent runs share this cache directory.
  tmp="\$(mktemp "\$cache_dir/.changelog.XXXXXX")"
  if ! curl -fsSL "\$url" -o "\$tmp"; then
    rm -f "\$tmp"
    echo "$1: cannot fetch the changelog contract at \$CONTRACT_REF" >&2
    exit 1
  fi
  mv "\$tmp" "\$contract"
fi
EOF
}

emit_renderer() {
  cat <<EOF
#!/usr/bin/env bash
# Prints the running log from the NEXT/ changelog fragments, newest first.
#
# Generated by Verjson/.github scripts/gen-changelog-caller.sh — do not edit by
# hand. Rendering is not implemented here: the canonical changelog contract
# lives in Verjson/.github (ADR 0038) and this repository pins one immutable
# commit of it, shared with .github/workflows/changelog.yml so that what you
# render locally is what CI validates.
set -euo pipefail

CONTRACT_REF="${ref}"

if [ "\$#" -gt 0 ]; then
  echo "render-next: unexpected argument '\$1'" >&2
  exit 2
fi
EOF
  emit_contract_resolution render-next
  cat <<'EOF'

exec python3 "$contract" render-next --repo-root "$root"
EOF
}

emit_contract_test() {
  cat <<EOF
#!/usr/bin/env bash
# Pins this repository's adoption of the canonical Verjson changelog contract
# (Verjson/.github ADR 0038): that the real tree validates, that every consumer
# of the contract shares one immutable pin, and that the pinned contract still
# enforces the rules this repository relies on.
#
# Generated by Verjson/.github scripts/gen-changelog-caller.sh — do not edit by
# hand. Every assertion about repository content is derived from the tree and
# none names a fragment, a title, or "nothing has been released yet". A release
# consumes every NEXT/ fragment, makes render-next exit 1, and generates
# CHANGELOG.md, so a test that pins the pre-release state is green until the
# first release and red forever after (#309).
set -euo pipefail

CONTRACT_REF="${ref}"
EOF
  emit_contract_resolution changelog-contract
  cat <<'CONTRACT_TEST_EOF'

renderer="$root/scripts/render-next.sh"
validation_workflow="$root/.github/workflows/changelog.yml"
release_workflow="$root/.github/workflows/release.yml"

fail() { printf 'FAIL - %s\n' "$1" >&2; exit 1; }

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

has_fragments() {
  [ -n "$(find "$root/NEXT" -name '*.md' ! -name 'README.md' -print -quit 2>/dev/null)" ]
}

python3 "$contract" validate --repo-root "$root"
echo "ok - canonical validation accepts this repository"

# Divergence between the pins is silent: both files keep working while what you
# render locally stops predicting what CI validates.
grep -q "changelog-validate.yml@$CONTRACT_REF" "$validation_workflow" \
  || fail "$validation_workflow does not pin changelog-validate.yml@$CONTRACT_REF"
grep -q "^CONTRACT_REF=\"$CONTRACT_REF\"$" "$renderer" \
  || fail "$renderer does not pin $CONTRACT_REF"
if [ -f "$release_workflow" ] && grep -q 'changelog-release\.yml@' "$release_workflow"; then
  grep -q "changelog-release.yml@$CONTRACT_REF" "$release_workflow" \
    || fail "$release_workflow pins a different contract commit"
fi
echo "ok - render, validation, and release automation share one immutable pin"

# A non-executable script fails CI with exit 126 long after the diff looks fine.
for file in "$renderer" "$0"; do
  [ -x "$file" ] || fail "$file is not executable"
done
echo "ok - contract scripts are executable"

# Derived from whatever NEXT/ holds, and skipped entirely once a release has
# consumed it. The renderer is invoked exactly as its own interface accepts:
# no arguments, and no environment override of the pinned contract (#304).
if rendered_next="$("$renderer" 2>"$work/render-error")"; then
  has_fragments || fail "the renderer produced output while NEXT/ holds no fragments"
  ROOT="$root" RENDERED="$rendered_next" python3 - <<'PY'
import os
import re
from pathlib import Path

root = Path(os.environ["ROOT"])
rendered = os.environ["RENDERED"]
fragments = sorted(p for p in (root / "NEXT").glob("*.md") if p.name != "README.md")
assert fragments, "the renderer produced output from no fragments"
for path in fragments:
    front = path.read_text(encoding="utf-8").split("---", 2)[1]
    meta = dict(
        (key.strip(), value.strip())
        for key, _, value in (line.partition(":") for line in front.splitlines())
        if key.strip()
    )
    assert f"## {meta['title']}" in rendered, f"{path.name}: title missing from render"
    if "issue" in meta:
        assert re.search(
            rf"^_Date: {re.escape(meta['date'])}; issue #{meta['issue']}_$",
            rendered,
            re.MULTILINE,
        ), f"{path.name}: issue linkage missing from render"
PY
  echo "ok - every unreleased fragment renders with its metadata linkage"
else
  # render-next exits 1 on an empty NEXT/ by contract. Any other cause is real,
  # so the diagnostic is swallowed only for the one failure that is expected.
  has_fragments && fail "the renderer failed while NEXT/ still holds fragments"
  grep -q 'no unreleased fragments' "$work/render-error" \
    || fail "the renderer failed for an unexpected reason: $(cat "$work/render-error")"
  echo "ok - no unreleased fragments to render (all consumed by a release)"
fi

# CHANGELOG.md is generated, never authored, so it is asserted equal to what the
# contract renders — not asserted absent. Absent and nothing released is the
# same equality, which is why this assertion survives the first release.
aggregate=""
if [ -f "$root/CHANGELOG.md" ]; then
  aggregate="$(cat "$root/CHANGELOG.md")"
fi
[ "$aggregate" = "$(python3 "$contract" render-released --repo-root "$root")" ] \
  || fail "CHANGELOG.md is not the contract's rendered release history"
echo "ok - CHANGELOG.md matches the rendered released history"

# The contract's own rules are pinned against throwaway fixtures, so they hold
# regardless of what this repository currently contains.
new_fixture() {
  rm -rf "$work/case"
  mkdir -p "$work/case/NEXT"
}

write_fragment() {
  # write_fragment <relative-path> <date> <identity-line> <title>
  cat >"$work/case/$1" <<FRAGMENT
---
date: $2
$3
title: $4
---

Body.
FRAGMENT
}

commit_fixture() {
  git -C "$work/case" init -q
  git -C "$work/case" config user.name Test
  git -C "$work/case" config user.email test@example.com
  git -C "$work/case" add -A
  git -C "$work/case" commit -qm "$1"
}

new_fixture
for slug in first second; do
  write_fragment "NEXT/2026-08-01-issue-43-$slug.md" 2026-08-01 "issue: 43" Duplicate
done
if python3 "$contract" validate --repo-root "$work/case" 2>"$work/error"; then
  fail "duplicate issue identity was accepted"
fi
grep -q 'duplicate identity issue:43' "$work/error"
echo "ok - duplicate issue identities are rejected"

new_fixture
write_fragment NEXT/2026-08-01-issue-43-wrong-date.md 2026-07-31 "issue: 43" "Wrong date"
if python3 "$contract" validate --repo-root "$work/case" 2>"$work/error"; then
  fail "mismatched filename metadata was accepted"
fi
grep -q 'does not match' "$work/error"
echo "ok - filename and metadata must agree"

new_fixture
write_fragment NEXT/2026-07-31-issue-99-zzz.md 2026-07-31 "issue: 99" Older
write_fragment NEXT/2026-08-01-issue-1-aaa.md 2026-08-01 "issue: 1" Newer
ordered="$(python3 "$contract" render-next --repo-root "$work/case")"
[ "$(grep -n '^## Newer$' <<<"$ordered" | cut -d: -f1)" \
  -lt "$(grep -n '^## Older$' <<<"$ordered" | cut -d: -f1)" ] \
  || fail "rendering order did not follow metadata"
echo "ok - rendering order follows metadata instead of slug allocation"

# The post-release state this repository will eventually be in, pinned against a
# fixture so it is proved rather than assumed on the day it first happens.
new_fixture
write_fragment NEXT/2026-08-01-issue-1-released.md 2026-08-01 "issue: 1" Released
commit_fixture initial
python3 "$contract" release --repo-root "$work/case" --version v1.0.0 >/dev/null
[ -z "$(find "$work/case/NEXT" -name '*.md' ! -name 'README.md' -print -quit)" ] \
  || fail "the release did not consume the fragments it snapshotted"
[ -f "$work/case/CHANGELOG/v1.0.0.md" ] || fail "the release wrote no immutable snapshot"
if python3 "$contract" render-next --repo-root "$work/case" >/dev/null 2>&1; then
  fail "render-next succeeded on an empty NEXT/"
fi
[ "$(cat "$work/case/CHANGELOG.md")" \
  = "$(python3 "$contract" render-released --repo-root "$work/case")" ] \
  || fail "the generated CHANGELOG.md is not the rendered release history"
echo "ok - a release consumes NEXT/, snapshots it, and regenerates CHANGELOG.md"

write_fragment NEXT/2026-08-02-issue-2-second.md 2026-08-02 "issue: 2" Second
git -C "$work/case" add -A
git -C "$work/case" commit -qm second
if python3 "$contract" release --repo-root "$work/case" --version v1.0.0 \
  2>"$work/error"; then
  fail "a released snapshot was overwritten"
fi
grep -q 'already exists' "$work/error"
echo "ok - released snapshots are immutable"
CONTRACT_TEST_EOF
}

# Never hand an operator a file that does not parse. The premise of generating
# these at all is that they should not be able to receive a silent footgun.
case "$mode" in
  workflow)
    out="$(emit_workflow)"
    if command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' 2>/dev/null; then
      printf '%s\n' "$out" | python3 -c 'import sys, yaml; yaml.safe_load(sys.stdin)' 2>/dev/null \
        || { echo "internal error: generated workflow is not valid YAML; refusing to emit" >&2; exit 3; }
    fi
    ;;
  renderer)
    out="$(emit_renderer)"
    printf '%s\n' "$out" | bash -n 2>/dev/null \
      || { echo "internal error: generated renderer is not valid bash; refusing to emit" >&2; exit 3; }
    ;;
  contract-test)
    out="$(emit_contract_test)"
    printf '%s\n' "$out" | bash -n 2>/dev/null \
      || { echo "internal error: generated contract test is not valid bash; refusing to emit" >&2; exit 3; }
    ;;
  *)
    usage
    ;;
esac
printf '%s\n' "$out"
