#!/usr/bin/env bash
# Generated by verJSON/.github scripts/gen-changelog-caller.sh — do not edit by hand.
# Maintainers edit this canonical source in verJSON/.github; adopters regenerate:
#   scripts/gen-changelog-caller.sh adr-index-generator <contract-sha> > scripts/gen-adr-index.sh
#
# Generates the reverse-chronological ADR index table in
# docs/decisions/README.md from each NNNN-*/README.md, so no PR ever hand-edits
# the shared table (add your ADR directory; the table is derived).
#
#   scripts/gen-adr-index.sh            # rewrite the table in place (between markers)
#   scripts/gen-adr-index.sh --check    # exit 1 if the committed table is stale
#
# Each ADR's row is [NNNN](dir/README.md) | <Date field> | <H1 title>. The H1
# (`# NNNN — Title`) is the canonical decision statement, so the index can't drift
# from the ADR. Pure bash + awk — runs on the bare self-hosted pool.
set -euo pipefail

case "$#:${1:-}" in
  0:|1:--check) ;;
  *) echo "gen-adr-index: expected no argument (regenerate) or exactly --check (verify)" >&2; exit 2 ;;
esac

root="${VERJSON_ADR_INDEX_ROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
root="$(cd "$root" && pwd)" \
  || { echo "gen-adr-index: repository root is not accessible: $root" >&2; exit 1; }
dec_dir="$root/docs/decisions"
index="$dec_dir/README.md"
begin='<!-- BEGIN ADR INDEX -->'
end='<!-- END ADR INDEX -->'

tmp_table=""
tmp_rendered=""
trap 'rm -f "$tmp_table" "$tmp_rendered"' EXIT

valid_date() {
  local value="$1" year month day max_day
  [[ "$value" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || return 1
  year=$((10#${value:0:4}))
  month=$((10#${value:5:2}))
  day=$((10#${value:8:2}))
  [ "$year" -ge 1 ] && [ "$month" -ge 1 ] && [ "$month" -le 12 ] && [ "$day" -ge 1 ] || return 1
  case "$month" in
    2)
      max_day=28
      if (( year % 400 == 0 || (year % 4 == 0 && year % 100 != 0) )); then max_day=29; fi
      ;;
    4|6|9|11) max_day=30 ;;
    *) max_day=31 ;;
  esac
  [ "$day" -le "$max_day" ]
}

validate_unique_numbers() {
  local d slug num rc=0
  declare -A first_path=()
  declare -A colliding=()

  # Every colliding directory is named, not just the first pair. Aborting on the
  # first pair hides the third member of a three-way collision, so whoever fixes
  # the two that were named hits the same error again on a directory nothing
  # mentioned.
  while IFS= read -r d; do
    slug="$(basename "$d")"
    num="${slug%%-*}"
    if [ -n "${first_path[$num]:-}" ]; then
      colliding[$num]="${colliding[$num]:-${first_path[$num]}} and $d"
      rc=1
    else
      first_path[$num]="$d"
    fi
  done < <(find "$dec_dir" -mindepth 1 -maxdepth 1 -type d \
    -name '[0-9][0-9][0-9][0-9]-*' | LC_ALL=C sort)

  if [ "$rc" -ne 0 ]; then
    for num in $(printf '%s\n' "${!colliding[@]}" | LC_ALL=C sort); do
      echo "gen-adr-index: duplicate ADR number $num: ${colliding[$num]}" >&2
    done
  fi
  return "$rc"
}

gen_table() {
  # A generated table is not the formatter's to own. prettier reformats every
  # markdown table it is given — padding each cell to the column width, and
  # inserting a blank line before the closing marker — so an adopter that runs
  # both prettier and `--check` over docs/decisions/README.md can satisfy one or
  # the other, never both (#1382). The padded form is not a fix either: it is
  # what prettier emits only under the default `proseWrap`, and a `never`
  # adopter gets a third, compact shape.
  #
  # `<!-- prettier-ignore -->` settles it inside the region this generator
  # already owns, so the two authorities agree by construction: prettier leaves
  # the block byte-identical under every proseWrap/printWidth setting, and no
  # adopter has to carry a .prettierignore entry a later regeneration could
  # drop. A repository that does not use prettier carries an inert comment.
  printf '<!-- prettier-ignore -->\n'
  printf '| # | Date | Decision |\n'
  printf '|---|------|----------|\n'
  local d slug num readme title date
  # Reverse sort by directory name → highest ADR number first. The collation is
  # pinned to C because a locale-aware sort weights punctuation differently, and
  # an index that orders one way on a contributor's machine and another way in
  # CI fails `--check` for a reason no diff explains.
  while IFS= read -r d; do
    slug="$(basename "$d")"
    num="${slug%%-*}"
    readme="$d/README.md"
    [ -f "$readme" ] || { echo "gen-adr-index: $slug/ has no README.md — an ADR directory must contain one" >&2; exit 1; }
    # H1 title, stripped of the leading "NNNN — " / "NNNN - " prefix.
    title="$(awk '
      /^# / && !seen {
        sub(/^# */, "")
        sub(/^[0-9]+ *— */, "")
        sub(/^[0-9]+ *- */, "")
        print; seen = 1
      }' "$readme")"
    # "- **Date:** YYYY-MM-DD" → the value.
    date="$(awk '
      index($0, "**Date:**") {
        s = substr($0, index($0, "**Date:**") + 9)
        gsub(/^[ \t]+|[ \t]+$/, "", s)
        print s; exit
      }' "$readme")"
    if [ -z "$title" ] || [ -z "$date" ]; then
      echo "gen-adr-index: $slug/README.md missing an '# NNNN — Title' H1 or '- **Date:**' line" >&2
      exit 1
    fi
    if ! valid_date "$date"; then
      echo "gen-adr-index: $slug/README.md has invalid date '$date' — expected a valid YYYY-MM-DD calendar date" >&2
      exit 1
    fi
    printf '| [%s](%s/README.md) | %s | %s |\n' "$num" "$slug" "$date" "$title"
  done < <(find "$dec_dir" -mindepth 1 -maxdepth 1 -type d -name '[0-9][0-9][0-9][0-9]-*' | LC_ALL=C sort -r)
  # The one piece of spacing prettier still normalizes around an ignored block:
  # it separates the table from the closing marker. Emitting it here keeps the
  # generated region a fixed point of the formatter rather than a fight with it.
  printf '\n'
}

render() {
  tmp_table="$(mktemp)"
  gen_table >"$tmp_table"
  awk -v tf="$tmp_table" -v b="$begin" -v e="$end" '
    $0 == b { print; while ((getline line < tf) > 0) print line; close(tf); skip = 1; next }
    $0 == e { skip = 0; print; next }
    !skip { print }
  ' "$index"
}

if ! grep -qF "$begin" "$index" || ! grep -qF "$end" "$index"; then
  echo "gen-adr-index: both markers '$begin' and '$end' must be present in $index" >&2
  exit 1
fi
validate_unique_numbers

if [ "${1:-}" = "--check" ]; then
  tmp_rendered="$(mktemp)"
else
  tmp_rendered="$(mktemp "$dec_dir/.adr-index.XXXXXX")"
fi
render >"$tmp_rendered"

if [ "${1:-}" = "--check" ]; then
  if ! diff -u "$index" "$tmp_rendered"; then
    echo "gen-adr-index: docs/decisions/README.md is stale — run scripts/gen-adr-index.sh and commit." >&2
    exit 1
  fi
  echo "ADR index is up to date."
else
  chmod --reference="$index" "$tmp_rendered"
  mv "$tmp_rendered" "$index"
  echo "Regenerated ADR index in $index"
fi
