#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".github/workflows/node-ci.yml"
TARGET = ROOT / ".github/workflows/node-ci-protected.yml"

INPUTS = """      event-name:\n        description: Authenticated pull-request event identity.\n        required: true\n        type: string\n+      head-repository:\n        description: Authenticated pull-request head repository.\n        required: true\n        type: string\n+      head-sha:\n        description: Authenticated immutable pull-request head SHA.\n        required: true\n        type: string\n+"""

VERIFY_STEP = """      - name: Revalidate protected pull-request identity\n        env:\n          ADMITTED_EVENT: ${{ inputs.event-name }}\n          ADMITTED_HEAD_REPOSITORY: ${{ inputs.head-repository }}\n          ADMITTED_HEAD_SHA: ${{ inputs.head-sha }}\n          GH_TOKEN: ${{ github.token }}\n          REPOSITORY: ${{ github.repository }}\n          RUN_ID: ${{ github.run_id }}\n        run: |\n          set -euo pipefail\n          [ "$ADMITTED_EVENT" = pull_request ]\n          [ -n "$ADMITTED_HEAD_REPOSITORY" ]\n          [[ "$ADMITTED_HEAD_SHA" =~ ^[0-9a-f]{40}$ ]]\n          [[ "$RUN_ID" =~ ^[1-9][0-9]*$ ]]\n          run_record="$(gh api "repos/$REPOSITORY/actions/runs/$RUN_ID" --jq '[.event,.head_sha,(.pull_requests|length),(.pull_requests[0].number//"")]|@tsv')"\n          IFS=$'\\t' read -r run_event run_head binding_count pr_number <<<"$run_record"\n          [ "$run_event" = "$ADMITTED_EVENT" ]\n          [ "$run_head" = "$ADMITTED_HEAD_SHA" ]\n          [ "$binding_count" = 1 ]\n          [[ "$pr_number" =~ ^[1-9][0-9]*$ ]]\n          pr_record="$(gh api "repos/$REPOSITORY/pulls/$pr_number" --jq '[.state,.head.repo.full_name,.head.sha]|@tsv')"\n          IFS=$'\\t' read -r pr_state pr_head_repository pr_head_sha <<<"$pr_record"\n          [ "$pr_state" = open ]\n          [ "$pr_head_repository" = "$ADMITTED_HEAD_REPOSITORY" ]\n          [ "$pr_head_sha" = "$ADMITTED_HEAD_SHA" ]\n+"""


INPUTS = INPUTS.replace("\n+", "\n")
VERIFY_STEP = VERIFY_STEP.replace("\n+", "\n")


def verifier_step(condition: str | None = None) -> str:
    if condition is None:
        return VERIFY_STEP
    marker = "        env:\n"
    if VERIFY_STEP.count(marker) != 1:
        raise SystemExit("protected verifier env marker drifted")
    return VERIFY_STEP.replace(marker, f"        if: {condition}\n{marker}")


def replace_once(document: str, old: str, new: str) -> str:
    if document.count(old) != 1:
        raise SystemExit(
            f"protected node-ci generator expected one {old.splitlines()[0]!r} boundary, "
            f"found {document.count(old)}"
        )
    return document.replace(old, new)


def render() -> str:
    document = SOURCE.read_text(encoding="utf-8")
    document = replace_once(document, "# Reusable CI for the verJSON Node libraries:", "# Generated by scripts/gen-node-ci-protected.py; do not edit.\n# Protected required-workflow Node.js CI variant:")
    document = replace_once(document, "      db-image:\n", INPUTS + "      db-image:\n")
    document = replace_once(document, "          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}", "          HEAD_SHA: ${{ inputs.head-sha }}")
    document = replace_once(document, "    permissions:\n      contents: read\n      packages: read\n", "    permissions:\n      actions: read\n      contents: read\n      packages: read\n      pull-requests: read\n")
    document = replace_once(document, "          EVENT_NAME: ${{ github.event_name }}\n          HEAD_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}", "          EVENT_NAME: ${{ inputs.event-name }}\n          HEAD_REPOSITORY: ${{ inputs.head-repository }}")
    document = replace_once(document, "    if: (inputs.secretless-pr || inputs.secretless-trusted-ref) && needs.eligibility.outputs.should-run != 'false'\n", "    if: needs.eligibility.outputs.should-run != 'false'\n")
    document = replace_once(document, "          [ \"$SECRETLESS_PR\" != \"$SECRETLESS_TRUSTED_REF\" ] || {\n", "          [ \"$SECRETLESS_PR\" = true ] && [ \"$SECRETLESS_TRUSTED_REF\" = false ] || {\n            echo \"::error::protected node-ci requires secretless-pr=true and secretless-trusted-ref=false\"\n            exit 1\n          }\n          [ \"$SECRETLESS_PR\" != \"$SECRETLESS_TRUSTED_REF\" ] || {\n")
    document = replace_once(document, "        with:\n          persist-credentials: false\n", "        with:\n          ref: ${{ inputs.head-sha }}\n          persist-credentials: false\n")
    document = replace_once(document, "          ref: ${{ inputs.head-sha }}\n          persist-credentials: false\n      - name: Reject consumer-controlled npm configuration\n", "          ref: ${{ inputs.head-sha }}\n          persist-credentials: false\n" + verifier_step() + "      - name: Reject consumer-controlled npm configuration\n")
    auxiliary_if = "inputs.secretless-auxiliary-source != ''"
    document = replace_once(document, "      - name: Acquire immutable auxiliary source\n", verifier_step(auxiliary_if) + "      - name: Acquire immutable auxiliary source\n")
    document = replace_once(document, "      - name: Populate verified private dependency cache\n", verifier_step() + "      - name: Populate verified private dependency cache\n")
    document = replace_once(document, "    permissions:\n      contents: read\n    steps:\n", "    permissions:\n      actions: read\n      contents: read\n      pull-requests: read\n    steps:\n")
    checkout = "        with:\n          submodules: ${{ (inputs.secretless-pr || inputs.secretless-trusted-ref) && 'false' || 'recursive' }}\n"
    document = replace_once(document, checkout, "        with:\n          ref: ${{ inputs.head-sha }}\n          submodules: ${{ (inputs.secretless-pr || inputs.secretless-trusted-ref) && 'false' || 'recursive' }}\n")
    rebuild_if = "needs.eligibility.outputs.should-run != 'false' && (inputs.secretless-pr || inputs.secretless-trusted-ref) && inputs.secretless-rebuild-packages != ''"
    plan_if = "needs.eligibility.outputs.should-run != 'false' && (inputs.secretless-pr || inputs.secretless-trusted-ref) && inputs.secretless-ci-script-plan != ''"
    default_if = "needs.eligibility.outputs.should-run != 'false' && (!(inputs.secretless-pr || inputs.secretless-trusted-ref) || inputs.secretless-ci-script-plan == '')"
    document = replace_once(document, "      - name: Rebuild exact approved lifecycle packages without credentials\n", verifier_step(rebuild_if) + "      - name: Rebuild exact approved lifecycle packages without credentials\n")
    document = replace_once(document, "      - name: Run exact credentialless consumer script plan\n", verifier_step(plan_if) + "      - name: Run exact credentialless consumer script plan\n")
    default_commands = """      - run: npm run build
        if: needs.eligibility.outputs.should-run != 'false' && (!(inputs.secretless-pr || inputs.secretless-trusted-ref) || inputs.secretless-ci-script-plan == '')
      - run: npm run typecheck --if-present
        if: needs.eligibility.outputs.should-run != 'false' && (!(inputs.secretless-pr || inputs.secretless-trusted-ref) || inputs.secretless-ci-script-plan == '')
      - run: npm test
        if: needs.eligibility.outputs.should-run != 'false' && (!(inputs.secretless-pr || inputs.secretless-trusted-ref) || inputs.secretless-ci-script-plan == '')
      - run: npm run lint --if-present
        if: needs.eligibility.outputs.should-run != 'false' && (!(inputs.secretless-pr || inputs.secretless-trusted-ref) || inputs.secretless-ci-script-plan == '')
"""
    grouped_default = """      - name: Run default build, typecheck, test, and lint plan
        if: needs.eligibility.outputs.should-run != 'false' && (!(inputs.secretless-pr || inputs.secretless-trusted-ref) || inputs.secretless-ci-script-plan == '')
        run: |
          npm run build
          npm run typecheck --if-present
          npm test
          npm run lint --if-present
"""
    document = replace_once(document, default_commands, verifier_step(default_if) + grouped_default)
    compatibility_if = "needs.eligibility.outputs.should-run != 'false' && (inputs.secretless-pr || inputs.secretless-trusted-ref) && inputs.secretless-compatibility-ranges != ''"
    document = replace_once(document, "      - name: Run runtime-resolved compatibility lanes without credentials\n", verifier_step(compatibility_if) + "      - name: Run runtime-resolved compatibility lanes without credentials\n")
    return document


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
