#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $0 <canonical-sha> <repository> <declaration-path> <package> <script> <approved-packages>" >&2
  exit 2
}

[ "$#" -eq 6 ] || usage
canonical_sha="$1"
repository="$2"
declaration_path="$3"
package_name="$4"
script_name="$5"
approved_packages="$6"

[[ "$canonical_sha" =~ ^[0-9a-f]{40}$ ]] || { echo 'canonical SHA must be 40 lowercase hex characters' >&2; exit 2; }
[[ "$repository" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || { echo 'repository must be owner/name' >&2; exit 2; }
[[ "$declaration_path" =~ ^\.github/ci/[A-Za-z0-9._-]+\.json$ ]] || { echo 'declaration path must be a protected .github/ci JSON file' >&2; exit 2; }
[[ "$package_name" =~ ^@[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$ ]] || { echo 'package must be an exact scoped package name' >&2; exit 2; }
[[ "$script_name" =~ ^[A-Za-z0-9][A-Za-z0-9:._-]{0,127}$ ]] || { echo 'script must be one package.json script name' >&2; exit 2; }
[ -n "$approved_packages" ] || { echo 'approved package list must not be empty' >&2; exit 2; }

while IFS= read -r approved; do
  [ -n "$approved" ] || continue
  [[ "$approved" =~ ^@[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*$ ]] || {
    echo "invalid approved package: $approved" >&2
    exit 2
  }
done <<< "$approved_packages"

cat <<EOF
# Generated by scripts/gen-type-surface-caller.sh $canonical_sha -- do not edit.
name: Protected $repository type surface

on:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  type-surface:
    if: github.repository == '$repository'
    uses: Verjson/.github/.github/workflows/type-surface-ci.yml@$canonical_sha
    secrets: inherit
    with:
      canonical-contract-sha: $canonical_sha
      declaration-path: $declaration_path
      expected-package: $package_name
      expected-script: $script_name
      approved-internal-packages: |-
$(sed 's/^/        /' <<< "$approved_packages")
EOF
