#!/usr/bin/env bash
# Generate a consumer's changelog contract adoption files.
#
# Generated, not hand-written, because the two halves must agree on one commit
# and nothing fails loudly when they don't: the renderer keeps rendering, the
# workflow keeps validating, and local output silently stops predicting CI.
# Hand-writing this three times already produced three shapes.
#
# Usage:
#   scripts/gen-changelog-caller.sh workflow <sha> > .github/workflows/changelog.yml
#   scripts/gen-changelog-caller.sh renderer <sha> > scripts/render-next.sh
#
# Consumers pin an immutable commit (docs/changelog/README.md) rather than a
# branch: the contract defines their release history's shape, so it must not
# move under them between a local render and the CI run that gates the PR.
set -euo pipefail

usage() {
  echo "usage: $(basename "$0") {workflow|renderer} <40-hex-commit>" >&2
  exit 2
}

[ "$#" -eq 2 ] || usage
mode="$1"
ref="$2"

# Strictly validated, not merely quoted. Both outputs interpolate this value —
# one into YAML, one into a shell assignment — so anything other than a bare
# commit is an injection vector. The sibling gen-privileged-merge-caller.sh
# documents a live instance of exactly that class.
[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || {
  echo "$(basename "$0"): ref must be a 40-character lowercase commit SHA" >&2
  exit 2
}

emit_workflow() {
  cat <<EOF
name: changelog

on:
  pull_request:

permissions:
  contents: read

jobs:
  changelog:
    uses: Verjson/.github/.github/workflows/changelog-validate.yml@${ref}
    with:
      contract_ref: ${ref}
EOF
}

emit_renderer() {
  cat <<EOF
#!/usr/bin/env bash
# Prints the running log from the NEXT/ changelog fragments, newest first.
#
# Generated by Verjson/.github scripts/gen-changelog-caller.sh — do not edit by
# hand. Rendering is not implemented here: the canonical changelog contract
# lives in Verjson/.github (ADR 0038) and this repository pins one immutable
# commit of it, shared with .github/workflows/changelog.yml so that what you
# render locally is what CI validates.
set -euo pipefail

CONTRACT_REF="${ref}"

if [ "\$#" -gt 0 ]; then
  echo "render-next: unexpected argument '\$1'" >&2
  exit 2
fi

root="\$(cd "\$(dirname "\$0")/.." && pwd)"
cache_dir="\${XDG_CACHE_HOME:-\$HOME/.cache}/verjson-changelog/\$CONTRACT_REF"
contract="\$cache_dir/changelog.py"

# Addressed by commit, so a cached copy cannot go stale: a new pin is a new path.
if [ ! -f "\$contract" ]; then
  mkdir -p "\$cache_dir"
  url="https://raw.githubusercontent.com/Verjson/.github/\$CONTRACT_REF/scripts/changelog.py"
  # mktemp, not a fixed name: two concurrent renders share this cache directory.
  tmp="\$(mktemp "\$cache_dir/.changelog.XXXXXX")"
  if ! curl -fsSL "\$url" -o "\$tmp"; then
    rm -f "\$tmp"
    echo "render-next: cannot fetch the changelog contract at \$CONTRACT_REF" >&2
    exit 1
  fi
  mv "\$tmp" "\$contract"
fi

exec python3 "\$contract" render-next --repo-root "\$root"
EOF
}

# Never hand an operator a file that does not parse. The premise of generating
# these at all is that they should not be able to receive a silent footgun.
case "$mode" in
  workflow)
    out="$(emit_workflow)"
    if command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' 2>/dev/null; then
      printf '%s\n' "$out" | python3 -c 'import sys, yaml; yaml.safe_load(sys.stdin)' 2>/dev/null \
        || { echo "internal error: generated workflow is not valid YAML; refusing to emit" >&2; exit 3; }
    fi
    ;;
  renderer)
    out="$(emit_renderer)"
    printf '%s\n' "$out" | bash -n 2>/dev/null \
      || { echo "internal error: generated renderer is not valid bash; refusing to emit" >&2; exit 3; }
    ;;
  *)
    usage
    ;;
esac
printf '%s\n' "$out"
