#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
kind="${1:?kind}"
ref="${2:?40-hex contract ref}"
config="${3:-container-deployment.json}"

[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || { echo "contract ref must be 40 lowercase hex" >&2; exit 1; }
[[ "$config" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*\.json$ && "/$config/" != *"/../"* ]] || {
  echo "config path must be a repository-relative JSON path" >&2
  exit 2
}

emit_python() {
  local source="$1"
  cat <<EOF
#!/usr/bin/env python3
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: $ref
# Source: Verjson/.github/$source@$ref
EOF
  git -C "$root" show "$ref:$source" | sed '1{/^#!\/usr\/bin\/env python3$/d;}'
}

case "$kind" in
  workflow)
    cat <<EOF
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
name: protected runner deployment
on:
  workflow_dispatch:
    inputs:
      manifest-identity:
        description: Immutable release manifest OCI digest identity
        required: true
        type: string
      fleet-selector:
        description: Reviewed consumer fleet selector
        required: true
        type: string
      action:
        description: Deploy or independently approved rollback
        required: true
        type: choice
        options: [deploy, rollback]
      rollback-receipt:
        description: Canonical digest of the retained failed or interrupted receipt
        required: false
        type: string
      dry-run:
        description: Produce exact host plan without external mutation
        required: true
        default: true
        type: boolean
permissions:
  actions: read
  attestations: read
  contents: read
jobs:
  deploy:
    uses: Verjson/.github/.github/workflows/container-deployment.yml@$ref
    with:
      manifest-identity: \${{ inputs.manifest-identity }}
      fleet-selector: \${{ inputs.fleet-selector }}
      action: \${{ inputs.action }}
      rollback-receipt: \${{ inputs.rollback-receipt }}
      dry-run: \${{ inputs.dry-run }}
      config-path: $config
      contract-ref: $ref
EOF
    ;;
  controller)
    emit_python scripts/container_deployment_controller.py
    ;;
  preflight)
    emit_python scripts/container_deployment_preflight.py
    ;;
  receipt-schema)
    git -C "$root" show \
      "$ref:docs/decisions/0078-container-release-and-runner-deployment-contract/deployment-receipt.schema.json"
    ;;
  contract-test)
    workflow_digest="$("$0" workflow "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    controller_digest="$("$0" controller "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    preflight_digest="$("$0" preflight "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    schema_digest="$("$0" receipt-schema "$ref" "$config" | sha256sum | cut -d' ' -f1)"
    cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: $ref

test "\$(sha256sum .github/workflows/container-deployment.yml | cut -d' ' -f1)" = "$workflow_digest"
test "\$(sha256sum scripts/container_deployment_controller.py | cut -d' ' -f1)" = "$controller_digest"
test "\$(sha256sum scripts/container_deployment_preflight.py | cut -d' ' -f1)" = "$preflight_digest"
test "\$(sha256sum scripts/deployment-receipt.schema.json | cut -d' ' -f1)" = "$schema_digest"
test -f "$config"
jq -e '
  .schemaVersion == 1 and
  .cliCommand == ["npx", "--no-install", "verjson-cloud"] and
  (.evidenceCommand | length == 2) and
  (.probeCommand | length == 2) and
  (.fleets | type == "object" and length > 0)
' "$config" >/dev/null
while IFS= read -r adapter; do
  test -f "\$adapter"
  test ! -L "\$adapter"
done < <(jq -r '.evidenceCommand[1], .probeCommand[1]' "$config")
grep -qF 'container-deployment.yml@$ref' .github/workflows/container-deployment.yml
grep -qF 'contract-ref: $ref' .github/workflows/container-deployment.yml
! grep -Eq 'secrets:|environment:|VERJSON_RUNNER_DEPLOY_TOKEN|:latest|:stable' \
  .github/workflows/container-deployment.yml
python3 -m py_compile scripts/container_deployment_controller.py scripts/container_deployment_preflight.py
python3 -m json.tool scripts/deployment-receipt.schema.json >/dev/null
python3 - .github/workflows/container-deployment.yml <<'PY'
import sys
import yaml

with open(sys.argv[1], encoding="utf-8") as stream:
    workflow = yaml.safe_load(stream)
trigger = workflow.get("on", workflow.get(True))
assert set(trigger) == {"workflow_dispatch"}
job = workflow["jobs"]["deploy"]
assert set(job) == {"uses", "with"}
assert job["uses"].startswith("Verjson/.github/.github/workflows/container-deployment.yml@")
assert set(workflow["permissions"]) == {"actions", "attestations", "contents"}
PY
EOF
    ;;
  *)
    echo "kind must be workflow, controller, preflight, receipt-schema, or contract-test" >&2
    exit 2
    ;;
esac
