#!/usr/bin/env python3
import argparse
import re


SHA_PATTERN = re.compile(r"[0-9a-f]{40}")


def render(node_ci_sha):
    if SHA_PATTERN.fullmatch(node_ci_sha) is None:
        raise ValueError("node-ci pin must be an immutable commit SHA")
    return """# Generated by scripts/gen-authn-type-surface-required-workflow.py @NODE_CI_SHA@ -- do not edit.
name: Authn required type surface

on:
  pull_request:

permissions:
  actions: read
  contents: read
  packages: read
  pull-requests: read
  statuses: read

jobs:
  type-surface:
    if: github.repository == 'Verjson/verjson-authn'
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
      statuses: read
    uses: Verjson/.github/.github/workflows/node-ci-protected.yml@@NODE_CI_SHA@
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      node-version: '24'
      secretless-pr: true
      event-name: ${{ github.event_name }}
      head-repository: ${{ github.event.pull_request.head.repo.full_name }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      protected-type-surface-declaration-path: .github/ci/type-surface-baseline.json
      protected-type-surface-expected-package: '@verjson/authn'
      protected-type-surface-expected-script: test:type-surface-compatibility
      approved-internal-packages: |-
        @verjson/authn
        @verjson/identity-contracts
        @verjson/tsconfig
      secretless-ci-script-plan: >-
        ["build"]
""".replace("@NODE_CI_SHA@", node_ci_sha)


def main(arguments=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("node_ci_sha")
    args = parser.parse_args(arguments)
    try:
        print(render(args.node_ci_sha), end="")
    except ValueError as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
