#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; kind="${1:?kind}"; ref="${2:?40-hex contract ref}"; shift 2
[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || exit 1
config=""; reconcile_paths=()
while [ "$#" -gt 0 ]; do
  case "$1" in
    --reconcile-allow) [ "$#" -ge 2 ] || exit 2; reconcile_paths+=("$2"); shift 2 ;;
    --*) exit 2 ;;
    *) [ -z "$config" ] || exit 2; config="$1"; shift ;;
  esac
done
config="${config:-container-candidate.json}"
[[ "$config" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*\.json$ && "/$config/" != *"/../"* ]] || { echo "config path must be a repository-relative JSON path" >&2; exit 2; }

# The reconciliation hook runs one step before the release App token is minted, so
# its file allowlist is declared here at generation time and pinned by the contract
# test — never read from a workflow_dispatch input a releaser could widen (ADR 0158).
if [ "${#reconcile_paths[@]}" -gt 0 ] && [ "$kind" != workflow ] && [ "$kind" != contract-test ]; then
  echo "--reconcile-allow is accepted only by workflow and contract-test" >&2; exit 2
fi
[ "${#reconcile_paths[@]}" -le 32 ] || { echo "at most 32 --reconcile-allow paths are accepted" >&2; exit 2; }
reconcile_json=""; reconcile_seen=()
for reconcile_path in ${reconcile_paths[@]+"${reconcile_paths[@]}"}; do
  [[ "$reconcile_path" =~ ^[A-Za-z0-9._][A-Za-z0-9._/-]*$ ]] \
    || { echo "--reconcile-allow must be a normalized repository-relative path" >&2; exit 2; }
  case "/$reconcile_path/" in
    */../*|*/./*|*//*) echo "--reconcile-allow must be a normalized repository-relative path" >&2; exit 2 ;;
  esac
  case "$reconcile_path" in
    .git*|*/.git*) echo "--reconcile-allow may not name a Git or workflow surface" >&2; exit 2 ;;
    RELEASES/*|CHANGELOG/*|NEXT/*) echo "--reconcile-allow may not name a release-engine surface" >&2; exit 2 ;;
  scripts/release-reconcile.sh|scripts/container_release_promotion.py|scripts/container_release_manifest.py|scripts/container_registry_destinations.py|scripts/container_artifact_extract.py|scripts/container_attestation_verify.py|scripts/container_cosign_provenance.py|scripts/container_release_reconcile.py|scripts/container-release-contract.test.sh)
      echo "--reconcile-allow may not name a release-engine surface" >&2; exit 2 ;;
  esac
  for seen in ${reconcile_seen[@]+"${reconcile_seen[@]}"}; do
    [ "$seen" != "$reconcile_path" ] || { echo "--reconcile-allow paths must be unique" >&2; exit 2; }
  done
  reconcile_seen+=("$reconcile_path")
  reconcile_json="${reconcile_json:+$reconcile_json,}\"$reconcile_path\""
done
[ -z "$reconcile_json" ] || reconcile_json="[$reconcile_json]"
reconcile_with=""
[ -z "$reconcile_json" ] || reconcile_with="
      reconcile-allowlist: '$reconcile_json'"
case "$kind" in
workflow) cat <<EOF
# Generated by Verjson/.github/scripts/gen-container-release.sh; do not edit.
name: container release
on:
  workflow_dispatch:
    inputs:
      version: {required: true, type: string}
      candidate-manifest: {required: true, type: string}
permissions:
  actions: read
  contents: read
  id-token: write
  packages: write
jobs:
  release:
    uses: Verjson/.github/.github/workflows/container-release.yml@$ref
    secrets: inherit
    with:
      version: \${{ inputs.version }}
      candidate-manifest: \${{ inputs.candidate-manifest }}
      config-path: $config
      contract-ref: $ref$reconcile_with
      release_app_client_id: \${{ vars.RELEASE_APP_CLIENT_ID }}
      release_environment: release-app
EOF
;;
validator) git -C "$root" show "$ref:scripts/container_release_promotion.py" ;;
manifest-validator)
cat <<HEADER
#!/usr/bin/env python3
# GENERATED FILE — do not edit by hand.
# Contract: $ref
# Source: Verjson/.github/scripts/container_release_manifest.py@$ref
HEADER
git -C "$root" show "$ref:scripts/container_release_manifest.py" \
  | sed '1{/^#!\/usr\/bin\/env python3$/d;}'
;;
destination-helper)
  cat <<HEADER
#!/usr/bin/env python3
# GENERATED FILE — do not edit by hand.
# Contract: $ref
# Source: Verjson/.github/scripts/container_registry_destinations.py@$ref
HEADER
  git -C "$root" show "$ref:scripts/container_registry_destinations.py" \
    | sed '1{/^#!\/usr\/bin\/env python3$/d;}'
  ;;
artifact-extractor) git -C "$root" show "$ref:scripts/container_artifact_extract.py" ;;
attestation-verifier) git -C "$root" show "$ref:scripts/container_attestation_verify.py" ;;
cosign-helper) git -C "$root" show "$ref:scripts/container_cosign_provenance.py" ;;
contract-test)
reconcile_args=()
for reconcile_path in ${reconcile_paths[@]+"${reconcile_paths[@]}"}; do
  reconcile_args+=(--reconcile-allow "$reconcile_path")
done
workflow_digest="$("$0" workflow "$ref" "$config" ${reconcile_args[@]+"${reconcile_args[@]}"} | sha256sum | cut -d' ' -f1)"
promotion_digest="$(git -C "$root" show "$ref:scripts/container_release_promotion.py" | sha256sum | cut -d' ' -f1)"
manifest_validator="$("$0" manifest-validator "$ref" "$config")"
manifest_digest="$(printf '%s\n' "$manifest_validator" | sha256sum | cut -d' ' -f1)"
destination_helper_digest="$("$0" destination-helper "$ref" "$config" | sha256sum | cut -d' ' -f1)"
extractor_digest="$(git -C "$root" show "$ref:scripts/container_artifact_extract.py" | sha256sum | cut -d' ' -f1)"
attestation_verifier_digest="$(git -C "$root" show "$ref:scripts/container_attestation_verify.py" | sha256sum | cut -d' ' -f1)"
cosign_helper_digest="$(git -C "$root" show "$ref:scripts/container_cosign_provenance.py" | sha256sum | cut -d' ' -f1)"
if [ -z "$reconcile_json" ]; then
reconcile_assertions="! grep -q 'reconcile-allowlist' .github/workflows/container-release.yml
test ! -e scripts/release-reconcile.sh"
else
reconcile_assertions="reconcile_allowlist='$reconcile_json'
grep -Fqx \"      reconcile-allowlist: '\$reconcile_allowlist'\" .github/workflows/container-release.yml
test -f scripts/release-reconcile.sh
test ! -L scripts/release-reconcile.sh
test -x scripts/release-reconcile.sh"
for reconcile_path in "${reconcile_paths[@]}"; do
reconcile_assertions="$reconcile_assertions
test -f '$reconcile_path'
test ! -L '$reconcile_path'"
done
fi
cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
ref='$ref'
printf '%s  %s\n' '$workflow_digest' .github/workflows/container-release.yml | sha256sum --check --strict
grep -Fq "container-release.yml@\$ref" .github/workflows/container-release.yml
grep -Fq "contract-ref: \$ref" .github/workflows/container-release.yml
grep -q "workflow_dispatch:" .github/workflows/container-release.yml
! grep -Eq '^  (push|pull_request):' .github/workflows/container-release.yml
grep -q 'RELEASE_APP_CLIENT_ID' .github/workflows/container-release.yml
grep -q 'release_environment: release-app' .github/workflows/container-release.yml
grep -q '^    secrets: inherit$' .github/workflows/container-release.yml
! grep -Eq 'PRIVATE_KEY' .github/workflows/container-release.yml
legacy_release_token='RELEASE_'"TOKEN"
legacy_org_release_token='VERJSON_RELEASE_'"TOKEN"
! grep -Eq "\$legacy_release_token|\$legacy_org_release_token" .github/workflows/container-release.yml
test -f scripts/container_release_promotion.py
test -f scripts/container_release_manifest.py
test -f scripts/container_registry_destinations.py
test -f scripts/container_artifact_extract.py
test -f scripts/container_attestation_verify.py
test -f scripts/container_cosign_provenance.py
printf '%s  %s\n' '$promotion_digest' scripts/container_release_promotion.py | sha256sum --check --strict
printf '%s  %s\n' '$manifest_digest' scripts/container_release_manifest.py | sha256sum --check --strict
printf '%s  %s\n' '$destination_helper_digest' scripts/container_registry_destinations.py | sha256sum --check --strict
printf '%s  %s\n' '$extractor_digest' scripts/container_artifact_extract.py | sha256sum --check --strict
printf '%s  %s\n' '$attestation_verifier_digest' scripts/container_attestation_verify.py | sha256sum --check --strict
printf '%s  %s\n' '$cosign_helper_digest' scripts/container_cosign_provenance.py | sha256sum --check --strict
! grep -Eq 'gh attestation verify|actions/attest-build-provenance@' .github/workflows/container-release.yml
grep -q 'Generated by Verjson/.github/scripts/gen-container-release.sh' .github/workflows/container-release.yml
$reconcile_assertions
echo 'container release contract passed'
EOF
;; *) exit 2;; esac
