#!/usr/bin/env python3
import argparse
import hashlib
import json
from pathlib import Path

from cli_projects_required_node_config import load_required_node_config


class ContractError(Exception):
    pass


def require(condition, message):
    if not condition:
        raise ContractError(message)


def load_config(path):
    return load_required_node_config(path, require)


def render(config, config_path):
    repository = config["repository"]
    owner, _ = repository.split("/", 1)
    packages = "\n".join(f"        {value}" for value in config["approved_internal_packages"])
    scripts = json.dumps(config["scripts"], separators=(",", ":"))
    current, floor = config["node_versions"]
    node_ci = config["node_ci_sha"]
    consumer_sha256 = hashlib.sha256(render_consumer(config, config_path).encode()).hexdigest()
    return f"""# Generated by scripts/gen-node-required-workflow.py {config_path} -- do not edit.
name: CLI projects required package surface

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]

permissions:
  contents: read

concurrency:
  group: cli-projects-required-${{{{ github.event.pull_request.number || github.ref }}}}
  cancel-in-progress: ${{{{ github.event_name == 'pull_request' }}}}

jobs:
  admission:
    if: github.repository == '{repository}'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      pull-requests: read
    outputs:
      event-name: ${{{{ steps.identity.outputs.event-name }}}}
      head-repository: ${{{{ steps.identity.outputs.head-repository }}}}
      head-sha: ${{{{ steps.identity.outputs.head-sha }}}}
    steps:
      - name: Validate the exact pull-request identity
        id: identity
        env:
          REPOSITORY: ${{{{ github.repository }}}}
          RUN_ID: ${{{{ github.run_id }}}}
          CONSUMER_WORKFLOW_SHA256: {consumer_sha256}
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
          set -euo pipefail
          [ "$REPOSITORY" = '{repository}' ]
          [[ "$RUN_ID" =~ ^[1-9][0-9]*$ ]]
          run_record="$(gh api "repos/$REPOSITORY/actions/runs/$RUN_ID" --jq '[.event,.head_sha,(.pull_requests|length),(.pull_requests[0].number//"")]|@tsv')"
          IFS=$'\\t' read -r event_name run_head_sha pr_count pr_number <<<"$run_record"
          [ "$event_name" = pull_request ]
          [[ "$run_head_sha" =~ ^[0-9a-f]{{40}}$ ]]
          [ "$pr_count" = 1 ]
          [[ "$pr_number" =~ ^[1-9][0-9]*$ ]]
          pr_record="$(gh api "repos/$REPOSITORY/pulls/$pr_number" --jq '[.number,.state,.head.repo.full_name,.head.sha,.base.ref]|@tsv')"
          IFS=$'\\t' read -r live_number live_state live_repository live_head_sha live_base_ref <<<"$pr_record"
          [ "$live_number" = "$pr_number" ]
          [ "$live_state" = open ]
          [ "$live_repository" = '{repository}' ]
          [ "$live_head_sha" = "$run_head_sha" ]
          [[ "$live_head_sha" =~ ^[0-9a-f]{{40}}$ ]]
          [ "$live_base_ref" = main ]
          candidate_workflow="$(mktemp)"
          trap 'rm -f -- "$candidate_workflow"' EXIT INT TERM
          gh api -H 'Accept: application/vnd.github.raw+json' "repos/{repository}/contents/.github/workflows/ci.yml?ref=$live_head_sha" >"$candidate_workflow"
          candidate_sha256="$(sha256sum "$candidate_workflow" | cut -d' ' -f1)"
          [[ "$candidate_sha256" =~ ^[0-9a-f]{{64}}$ ]]
          [ "$candidate_sha256" = "$CONSUMER_WORKFLOW_SHA256" ]
          {{
            echo "event-name=$event_name"
            echo "head-repository=$live_repository"
            echo "head-sha=$live_head_sha"
          }} >>"$GITHUB_OUTPUT"
  ci:
    needs: admission
    if: ${{{{ !github.event.pull_request.draft }}}}
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
      statuses: read
    uses: {owner}/.github/.github/workflows/node-ci-protected.yml@{node_ci}
    secrets:
      NODE_AUTH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
    with:
      node-version: '{current}'
      secretless-pr: true
      approved-internal-packages: |-
{packages}
      secretless-ci-script-plan: >-
        {scripts}
      event-name: ${{{{ needs.admission.outputs.event-name }}}}
      head-repository: ${{{{ needs.admission.outputs.head-repository }}}}
      head-sha: ${{{{ needs.admission.outputs.head-sha }}}}
  ci-node-floor:
    needs: admission
    if: ${{{{ !github.event.pull_request.draft }}}}
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: read
      statuses: read
    uses: {owner}/.github/.github/workflows/node-ci-protected.yml@{node_ci}
    secrets:
      NODE_AUTH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
    with:
      node-version: '{floor}'
      secretless-pr: true
      approved-internal-packages: |-
{packages}
      event-name: ${{{{ needs.admission.outputs.event-name }}}}
      head-repository: ${{{{ needs.admission.outputs.head-repository }}}}
      head-sha: ${{{{ needs.admission.outputs.head-sha }}}}
  package-surface:
    needs: [admission, ci, ci-node-floor]
    if: ${{{{ always() && !github.event.pull_request.draft && needs.admission.result == 'success' && needs.ci.result == 'success' && needs.ci-node-floor.result == 'success' }}}}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out the untrusted candidate tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{{{ needs.admission.outputs.head-sha }}}}
          persist-credentials: false
          path: consumer
      - name: Check out the protected verifier at the required-workflow revision
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: {owner}/.github
          ref: ${{{{ github.workflow_sha }}}}
          persist-credentials: false
          path: policy
      - name: Verify and exercise the package surface
        env:
          HOME: ${{{{ runner.temp }}}}/credentialless-home
          NPM_CONFIG_USERCONFIG: ${{{{ runner.temp }}}}/credentialless-npmrc
        run: python3 policy/scripts/cli-projects-package-surface.py verify consumer
"""


def render_consumer(config, config_path):
    owner, _ = config["repository"].split("/", 1)
    node_ci = config["node_ci_sha"]
    return f"""# Generated by scripts/gen-node-required-workflow.py --consumer {config_path} -- do not edit.
name: CI
on:
  push:
    branches: [main]
concurrency:
  group: ci-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: false
jobs:
  ci:
    permissions:
      contents: read
      packages: read
      statuses: read
    uses: {owner}/.github/.github/workflows/node-ci.yml@{node_ci}
    with:
      node-version: '24.19.0'
      timeout-minutes: 20
      runner: '["self-hosted", "general"]'
    secrets:
      NODE_AUTH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
"""


def main(arguments=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("config", type=Path)
    parser.add_argument("--consumer", action="store_true")
    args = parser.parse_args(arguments)
    config = load_config(args.config)
    renderer = render_consumer if args.consumer else render
    print(renderer(config, args.config.as_posix()), end="")


if __name__ == "__main__":
    try:
        main()
    except ContractError as error:
        print(error, file=__import__("sys").stderr)
        raise SystemExit(2)
