#!/usr/bin/env python3
import argparse
import hashlib
import json
from pathlib import Path
import re


SHA = re.compile(r"[0-9a-f]{40}")
REPOSITORY = re.compile(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+")
PACKAGE = re.compile(r"@[a-z0-9][a-z0-9._-]*/[a-z0-9][a-z0-9._-]*")
SCRIPT = re.compile(r"[a-z0-9][a-z0-9:._-]*")
NODE = re.compile(r"[0-9]+(?:\.[0-9]+){0,2}")


class ContractError(Exception):
    pass


def require(condition, message):
    if not condition:
        raise ContractError(message)


def load_config(path):
    def unique(pairs):
        value = {}
        for key, item in pairs:
            require(key not in value, f"duplicate config key: {key}")
            value[key] = item
        return value

    try:
        config = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique)
    except (OSError, json.JSONDecodeError) as error:
        raise ContractError(f"invalid config: {error}") from None
    require(set(config) == {
        "schema_version", "repository", "node_ci_sha", "node_versions",
        "approved_internal_packages", "scripts",
    }, "config keys drifted")
    require(config["schema_version"] == 1, "unsupported schema_version")
    require(isinstance(config["repository"], str) and REPOSITORY.fullmatch(config["repository"]),
            "repository must be an exact owner/name")
    require(config["repository"] == "Verjson/verjson-cli-projects",
            "this protected verifier is bound to Verjson/verjson-cli-projects")
    require(isinstance(config["node_ci_sha"], str) and SHA.fullmatch(config["node_ci_sha"]),
            "node_ci_sha must be immutable")
    versions = config["node_versions"]
    require(isinstance(versions, list) and len(versions) == 2 and len(set(versions)) == 2,
            "node_versions must contain two unique versions")
    require(all(isinstance(value, str) and NODE.fullmatch(value) for value in versions),
            "node_versions contain an invalid value")
    packages = config["approved_internal_packages"]
    require(isinstance(packages, list) and packages and len(packages) == len(set(packages)),
            "approved_internal_packages must be nonempty and unique")
    require(all(isinstance(value, str) and PACKAGE.fullmatch(value) for value in packages),
            "approved_internal_packages contain an invalid name")
    scripts = config["scripts"]
    require(isinstance(scripts, list) and scripts and len(scripts) == len(set(scripts)),
            "scripts must be nonempty and unique")
    require(all(isinstance(value, str) and SCRIPT.fullmatch(value) for value in scripts),
            "scripts contain an invalid name")
    return config


def render(config, config_path):
    repository = config["repository"]
    owner, _ = repository.split("/", 1)
    packages = "\n".join(f"        {value}" for value in config["approved_internal_packages"])
    scripts = json.dumps(config["scripts"], separators=(",", ":"))
    current, floor = config["node_versions"]
    node_ci = config["node_ci_sha"]
    consumer = render_consumer(config, config_path)
    consumer_sha256 = hashlib.sha256(consumer.encode()).hexdigest()
    return f"""# Generated by scripts/gen-node-required-workflow.py {config_path} -- do not edit.
name: CLI projects required package surface

on:
  pull_request:

permissions:
  contents: read

jobs:
  admission:
    if: github.repository == '{repository}'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Validate the exact pull-request identity
        env:
          EVENT_NAME: ${{{{ github.event_name }}}}
          HEAD_REPOSITORY: ${{{{ github.event.pull_request.head.repo.full_name }}}}
          HEAD_SHA: ${{{{ github.event.pull_request.head.sha }}}}
          MERGE_SHA: ${{{{ github.sha }}}}
          PR_NUMBER: ${{{{ github.event.pull_request.number }}}}
          REF: ${{{{ github.ref }}}}
          REPOSITORY: ${{{{ github.repository }}}}
          CONSUMER_WORKFLOW_SHA256: {consumer_sha256}
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
          set -euo pipefail
          [ "$EVENT_NAME" = pull_request ]
          [ "$REPOSITORY" = '{repository}' ]
          [ "$HEAD_REPOSITORY" = '{repository}' ]
          [[ "$PR_NUMBER" =~ ^[1-9][0-9]*$ ]]
          [[ "$HEAD_SHA" =~ ^[0-9a-f]{{40}}$ ]]
          [[ "$MERGE_SHA" =~ ^[0-9a-f]{{40}}$ ]]
          [ "$REF" = "refs/pull/$PR_NUMBER/merge" ]
          record="$(gh api "repos/{repository}/pulls/$PR_NUMBER" \\
            --jq '[.number,.head.repo.full_name,.head.sha,.merge_commit_sha] | @tsv')"
          IFS=$'\\t' read -r live_number live_repository live_head live_merge <<<"$record"
          [ "$live_number" = "$PR_NUMBER" ]
          [ "$live_repository" = "$HEAD_REPOSITORY" ]
          [ "$live_head" = "$HEAD_SHA" ]
          [ "$live_merge" = "$MERGE_SHA" ]
          candidate_workflow="$(mktemp)"
          trap 'rm -f -- "$candidate_workflow"' EXIT INT TERM
          gh api -H 'Accept: application/vnd.github.raw+json' "repos/{repository}/contents/.github/workflows/ci.yml?ref=$HEAD_SHA" >"$candidate_workflow"
          [ "$(sha256sum "$candidate_workflow" | cut -d' ' -f1)" = "$CONSUMER_WORKFLOW_SHA256" ]

  ci:
    needs: admission
    permissions:
      contents: read
      packages: read
      statuses: read
    uses: {owner}/.github/.github/workflows/node-ci.yml@{node_ci}
    secrets:
      NODE_AUTH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
    with:
      node-version: '{current}'
      secretless-pr: true
      approved-internal-packages: |-
{packages}
      secretless-ci-script-plan: >-
        {scripts}

  ci-node-floor:
    needs: admission
    permissions:
      contents: read
      packages: read
      statuses: read
    uses: {owner}/.github/.github/workflows/node-ci.yml@{node_ci}
    secrets:
      NODE_AUTH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
    with:
      node-version: '{floor}'
      secretless-pr: true
      approved-internal-packages: |-
{packages}

  package-surface:
    needs: [admission, ci, ci-node-floor]
    if: ${{{{ always() && needs.admission.result == 'success' && needs.ci.result == 'success' && needs.ci-node-floor.result == 'success' }}}}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out the untrusted candidate tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}
          persist-credentials: false
          path: consumer
      - name: Check out the protected verifier at the required-workflow revision
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: {owner}/.github
          ref: ${{{{ github.workflow_sha }}}}
          persist-credentials: false
          path: policy
      - name: Verify and exercise the package surface
        env:
          HOME: ${{{{ runner.temp }}}}/credentialless-home
          NPM_CONFIG_USERCONFIG: ${{{{ runner.temp }}}}/credentialless-npmrc
        run: python3 policy/scripts/cli-projects-package-surface.py verify consumer
"""


def render_consumer(config, config_path):
    owner, _ = config["repository"].split("/", 1)
    node_ci = config["node_ci_sha"]
    return f"""# Generated by scripts/gen-node-required-workflow.py --consumer {config_path} -- do not edit.
name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: false

jobs:
  ci:
    permissions:
      contents: read
      packages: read
      statuses: read
    uses: {owner}/.github/.github/workflows/node-ci.yml@{node_ci}
    with:
      node-version: '24.19.0'
      timeout-minutes: 20
      runner: '["self-hosted", "general"]'
    secrets:
      NODE_AUTH_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
"""


def main(arguments=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("config", type=Path)
    parser.add_argument("--consumer", action="store_true")
    args = parser.parse_args(arguments)
    config = load_config(args.config)
    renderer = render_consumer if args.consumer else render
    print(renderer(config, args.config.as_posix()), end="")


if __name__ == "__main__":
    try:
        main()
    except ContractError as error:
        print(f"error: {error}", file=__import__("sys").stderr)
        raise SystemExit(2)
