#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $(basename "$0") {pack-helper|contract-test} <40-hex-commit>" >&2
  exit 2
}

[ "$#" -eq 2 ] || usage
mode="$1"
ref="$2"
[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || usage

root="$(cd "$(dirname "$0")/.." && pwd)"
helper_path=scripts/npm-pack-json.mjs
helper="$(mktemp)"
trap 'rm -f "$helper"' EXIT
git -C "$root" show "$ref:$helper_path" >"$helper" || {
  echo "$(basename "$0"): $ref does not carry $helper_path" >&2
  exit 2
}

case "$mode" in
  pack-helper)
    cat "$helper"
    ;;
  contract-test)
    helper_sha256="$(sha256sum "$helper" | cut -d' ' -f1)"
    cat <<EOF
#!/usr/bin/env bash
# Generated by Verjson/.github scripts/gen-type-surface-contract.sh contract-test $ref -- do not edit.
set -euo pipefail

root="\$(cd "\$(dirname "\$0")/.." && pwd)"
helper="\$root/scripts/npm-pack-json.mjs"

[ -f "\$helper" ] || { echo 'FAIL - generated npm pack receipt parser is missing' >&2; exit 1; }
printf '%s  %s\n' '$helper_sha256' "\$helper" | sha256sum --check --strict >/dev/null
node --input-type=module - "\$helper" <<'JS'
import { pathToFileURL } from 'node:url';

const { resolvePackedTarball } = await import(pathToFileURL(process.argv[2]));
const expected = '@verjson/example';
const filename = 'verjson-example-1.2.3.tgz';
const arrayReceipt = JSON.stringify([{ name: expected, filename }]);
const objectReceipt = JSON.stringify({ [expected]: { name: expected, filename } });

if (resolvePackedTarball(arrayReceipt, expected).filename !== filename) process.exit(1);
if (resolvePackedTarball(objectReceipt, expected).filename !== filename) process.exit(1);
JS
echo 'ok - npm pack receipt parser matches the pinned type-surface contract'
EOF
    ;;
  *) usage ;;
esac
