#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; kind="${1:?kind}"; ref="${2:?40-hex contract ref}"; config="${3:-container-candidate.json}"
[[ "$ref" =~ ^[0-9a-f]{40}$ ]] || exit 1
[[ "$config" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]*\.json$ && "/$config/" != *"/../"* ]] || { echo "config path must be a repository-relative JSON path" >&2; exit 2; }
case "$kind" in
workflow) cat <<EOF
# Generated by Verjson/.github/scripts/gen-container-release.sh; do not edit.
name: container release
on:
  workflow_dispatch:
    inputs:
      version: {required: true, type: string}
      candidate-manifest: {required: true, type: string}
permissions:
  actions: read
  attestations: write
  contents: read
  id-token: write
jobs:
  release:
    uses: Verjson/.github/.github/workflows/container-release.yml@$ref
    with:
      version: \${{ inputs.version }}
      candidate-manifest: \${{ inputs.candidate-manifest }}
      config-path: $config
      contract-ref: $ref
    secrets:
      release-token: \${{ secrets.RELEASE_TOKEN }}
EOF
;;
validator) git -C "$root" show "$ref:scripts/container_release_promotion.py" ;;
manifest-validator)
cat <<HEADER
#!/usr/bin/env python3
# GENERATED FILE — do not edit by hand.
# Contract: $ref
# Source: Verjson/.github/scripts/container_release_manifest.py@$ref
HEADER
git -C "$root" show "$ref:scripts/container_release_manifest.py" \
  | sed '1{/^#!\/usr\/bin\/env python3$/d;}'
;;
artifact-extractor) git -C "$root" show "$ref:scripts/container_artifact_extract.py" ;;
attestation-verifier) git -C "$root" show "$ref:scripts/container_attestation_verify.py" ;;
contract-test)
promotion_digest="$(git -C "$root" show "$ref:scripts/container_release_promotion.py" | sha256sum | cut -d' ' -f1)"
manifest_validator="$("$0" manifest-validator "$ref" "$config")"
manifest_digest="$(printf '%s\n' "$manifest_validator" | sha256sum | cut -d' ' -f1)"
extractor_digest="$(git -C "$root" show "$ref:scripts/container_artifact_extract.py" | sha256sum | cut -d' ' -f1)"
attestation_verifier_digest="$(git -C "$root" show "$ref:scripts/container_attestation_verify.py" | sha256sum | cut -d' ' -f1)"
cat <<EOF
#!/usr/bin/env bash
set -euo pipefail
ref='$ref'
grep -Fq "container-release.yml@\$ref" .github/workflows/container-release.yml
grep -Fq "contract-ref: \$ref" .github/workflows/container-release.yml
grep -q "workflow_dispatch:" .github/workflows/container-release.yml
! grep -Eq '^  (push|pull_request):' .github/workflows/container-release.yml
grep -q 'RELEASE_TOKEN' .github/workflows/container-release.yml
test -f scripts/container_release_promotion.py
test -f scripts/container_release_manifest.py
test -f scripts/container_artifact_extract.py
test -f scripts/container_attestation_verify.py
printf '%s  %s\n' '$promotion_digest' scripts/container_release_promotion.py | sha256sum --check --strict
printf '%s  %s\n' '$manifest_digest' scripts/container_release_manifest.py | sha256sum --check --strict
printf '%s  %s\n' '$extractor_digest' scripts/container_artifact_extract.py | sha256sum --check --strict
printf '%s  %s\n' '$attestation_verifier_digest' scripts/container_attestation_verify.py | sha256sum --check --strict
grep -q '^  attestations: write$' .github/workflows/container-release.yml
grep -q 'Generated by Verjson/.github/scripts/gen-container-release.sh' .github/workflows/container-release.yml
echo 'container release contract passed'
EOF
;; *) exit 2;; esac
