#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 4 ] || [[ ! "$1" =~ ^[0-9a-f]{40}$ ]]; then
  echo "usage: $0 <contract-sha> <package> <candidate> <stack-profile>" >&2
  exit 2
fi

ref="$1" package="$2" candidate="$3" profile="$4"
[[ "$package" =~ ^(@[a-z0-9._-]+/)?[a-z0-9._-]+$ ]]
[[ "$candidate" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$ ]]
[[ "$profile" =~ ^[a-z0-9-]+$ ]]

cat <<EOF
name: Renovate compatibility canary
# Generated by Verjson/.github scripts/gen-renovate-compatibility-caller.sh $ref
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  compatibility:
    uses: Verjson/.github/.github/workflows/renovate-compatibility-canary.yml@$ref
    with:
      package: '$package'
      candidate: '$candidate'
      stack-profile: '$profile'
EOF
