#!/usr/bin/env python3
import argparse
import re


SHA_PATTERN = re.compile(r"[0-9a-f]{40}")


def render(node_ci_sha):
    if SHA_PATTERN.fullmatch(node_ci_sha) is None:
        raise ValueError("node-ci pin must be an immutable commit SHA")
    return """# Generated by scripts/gen-authn-type-surface-required-workflow.py @NODE_CI_SHA@ -- do not edit.
name: Authn required type surface

on:
  pull_request:

permissions:
  contents: read
  packages: read
  statuses: read

jobs:
  type-surface:
    if: github.repository == 'Verjson/verjson-authn'
    permissions:
      contents: read
      packages: read
      statuses: read
    uses: Verjson/.github/.github/workflows/node-ci.yml@@NODE_CI_SHA@
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      node-version: '24'
      scope: '@verjson'
      secretless-pr: true
      approved-internal-packages: |-
        @verjson/authn
        @verjson/identity-contracts
        @verjson/tsconfig
      secretless-compatibility-ranges: >-
        {"package":"@verjson/authn","ranges":["3.0.0"],"script":"test:type-surface-compatibility"}
      secretless-auxiliary-source: >-
        {"repository":"Verjson/verjson-authn","pinFile":".github/ci/type-surface-base.json","checkoutPath":".authn-type-base","sparsePath":"NEXT"}
      secretless-ci-script-plan: >-
        ["build"]
""".replace("@NODE_CI_SHA@", node_ci_sha)


def main(arguments=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("node_ci_sha")
    args = parser.parse_args(arguments)
    try:
        print(render(args.node_ci_sha), end="")
    except ValueError as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
