#!/usr/bin/env bash
# Release verification for the canonical contract and its published tools.
# The release caller runs this after stamping the exact dispatched version.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -z "${PACKAGE_VERSION:-}" ]; then
  echo "release-verify: PACKAGE_VERSION must be set by the dispatched contract release" >&2
  exit 2
fi

pin="$(sed -nE 's/^# Generated by Verjson\/.github scripts\/gen-changelog-caller\.sh release-node ([0-9a-f]{40}) --only-package-dir \.$/\1/p' .github/workflows/release.yml)"
[ -n "$pin" ] || { echo "release-verify: .github/workflows/release.yml carries no package-release pin header" >&2; exit 1; }
git show "$pin:scripts/gen-changelog-caller.sh" | bash -s release-node "$pin" --only-package-dir . | cmp -s - .github/workflows/release.yml \
  || { echo "release-verify: .github/workflows/release.yml differs from its pinned generator $pin; regenerate it" >&2; exit 1; }

node --test scripts/ci-gate/contract-tools-package.test.js
python3 scripts/changelog.py validate
bash scripts/render-next.sh >/dev/null
bash scripts/gen-adr-index.sh --check
python3 scripts/adr-relative-links.test.py
bash scripts/doc-fragment-names.test.sh >/dev/null
echo "release verification passed"
