#!/usr/bin/env bash
# Release verification for Verjson/.github itself (ADR 0191, #1374). This
# repository is not a Node project, so the generated release-snapshot caller
# runs this hook instead of npm test. It verifies the surfaces a contract
# release publishes: the fragment store, the rendered release notes, the ADR
# index, ADR links, and fragment naming. The full CI-equivalent suites run on
# every pull request before a commit can reach main.
set -euo pipefail
cd "$(dirname "$0")/.."
# The release caller is a generated artifact with no adopter contract test to
# guard it here, so verify it is still exactly what the generator at its own
# header pin emits (a hand edit is the divergence the header warns about).
pin="$(sed -nE 's/^# Generated by Verjson\/.github scripts\/gen-changelog-caller\.sh release-snapshot ([0-9a-f]{40})$/\1/p' .github/workflows/release.yml)"
[ -n "$pin" ] || { echo "release-verify: .github/workflows/release.yml carries no release-snapshot pin header" >&2; exit 1; }
git show "$pin:scripts/gen-changelog-caller.sh" | bash -s release-snapshot "$pin" | cmp -s - .github/workflows/release.yml \
  || { echo "release-verify: .github/workflows/release.yml differs from gen-changelog-caller.sh release-snapshot at its pin $pin; regenerate it" >&2; exit 1; }
python3 scripts/changelog.py validate
bash scripts/render-next.sh >/dev/null
bash scripts/gen-adr-index.sh --check
python3 scripts/adr-relative-links.test.py
bash scripts/doc-fragment-names.test.sh >/dev/null
echo "release verification passed"
